### ISSUE TITLE
Unknown demo type

### ISSUE THREAD

**Issue by GreenBandana** [bugdone/headshotbox#101]
When feeding headshot box with GOTV demos of matches that were recorded on my own server the following error occurs for each demo file:

ERROR [hsbox.indexer] - Cannot parse demo
ERROR [hsbox.indexer] - hsbox.core.main
                     ...
        hsbox.core/-main     core.clj:  69
       hsbox.indexer/run  indexer.clj:  94
  hsbox.indexer/add-demo  indexer.clj:  54
hsbox.demo/get-demo-info     demo.clj: 205
java.lang.Exception: Unknown demo type

How can I fix this?

**Comment by bugdone** [comment]
You can't.
See https://github.com/bugdone/headshotbox/issues/65#issuecomment-121368971
