### ISSUE TITLE
demoinfogo.exe has stopped working

### ISSUE THREAD

**Issue by alfeh** [bugdone/headshotbox#102]
Whenever I try and run the program and it attempts to parse the demos, I just keep getting spammed down by the windows message saying it has stopped working. I'll click "Close the program", wait a second or so and it will reappear. I've tried un-installing and installing again only to get the same issue. I've done the settings on http://127.0.0.1:4000/ and the demo directory is correct. This is what the config file says:

                     [37m...[m  [32m                [m
        [33mhsbox.core/[1;33m-main[m  [32m   core.clj:  69[m
       [33mhsbox.indexer/[1;33mrun[m  [32mindexer.clj:  94[m
  [33mhsbox.indexer/[1;33madd-demo[m  [32mindexer.clj:  54[m
[33mhsbox.demo/[1;33mget-demo-info[m  [32m   demo.clj: 205[m
[1;31mjava.lang.Exception[m: [3mUnknown demo type[m

2015-Dec-16 18:27:29 +0000 Bjarni-PC DEBUG [hsbox.indexer] - Adding path C:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\uggabugga_2.dem
2015-Dec-16 18:27:29 +0000 Bjarni-PC INFO [hsbox.demo] - Processing C:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\uggabugga_2.dem
2015-Dec-16 18:27:30 +0000 Bjarni-PC ERROR [hsbox.indexer] - Cannot parse demo C:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\uggabugga_2.dem
2015-Dec-16 18:27:30 +0000 Bjarni-PC ERROR [hsbox.indexer] - 
         [37mhsbox.core.main[m  [32m                [m
                     [37m...[m  [32m                [m
        [33mhsbox.core/[1;33m-main[m  [32m   core.clj:  69[m
       [33mhsbox.indexer/[1;33mrun[m  [32mindexer.clj:  94[m
  [33mhsbox.indexer/[1;33madd-demo[m  [32mindexer.clj:  54[m
[33mhsbox.demo/[1;33mget-demo-info[m  [32m   demo.clj: 183[m
   [33mhsbox.demo/[1;33mparse-demo[m  [32m   demo.clj:  38[m
[1;31mjava.lang.AssertionError[m: [3mAssert failed: (zero? (:exit proc))[m

2015-Dec-16 18:27:30 +0000 Bjarni-PC DEBUG [hsbox.indexer] - Adding path C:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\tenac.dem
2015-Dec-16 18:27:30 +0000 Bjarni-PC INFO [hsbox.demo] - Processing C:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\tenac.dem
2015-Dec-16 18:27:31 +0000 Bjarni-PC ERROR [hsbox.indexer] - Cannot parse demo C:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\tenac.dem
2015-Dec-16 18:27:31 +0000 Bjarni-PC ERROR [hsbox.indexer] - 
         [37mhsbox.core.main[m  [32m                [m
                     [37m...[m  [32m                [m
        [33mhsbox.core/[1;33m-main[m  [32m   core.clj:  69[m
       [33mhsbox.indexer/[1;33mrun[m  [32mindexer.clj:  94[m
  [33mhsbox.indexer/[1;33madd-demo[m  [32mindexer.clj:  54[m
[33mhsbox.demo/[1;33mget-demo-info[m  [32m   demo.clj: 183[m
   [33mhsbox.demo/[1;33mparse-demo[m  [32m   demo.clj:  38[m
[1;31mjava.lang.AssertionError[m: [3mAssert failed: (zero? (:exit proc))[m

That's only a pretty small part of it, the file goes on and on but hopefully you get the info you need from there - if not, then I'll post the rest. Any clue as to why it keeps happening?

**Comment by bugdone** [comment]
Does [this](https://github.com/bugdone/headshotbox/wiki/FAQ#log-mentions-exception-in-thread-main-javalangassertionerror-assert-failed-zero-exit-proc) help?

**Comment by alfeh** [comment]
No, I am on a fresh install of Windows so I might be missing some items, but I do however have Visual C++ installed so it must be something else.

**Comment by alfeh** [comment]
And just to be certain I tried changing my demo directory to a different harddrive (where my old CS:GO was before installing new SSD) and that one doesn't work either, gave me the same issues.

**Comment by bugdone** [comment]
You can try just running the demoinfogo.exe binary. If it crashes as before it has nothing to do with the drive or the demos. It's most probably a dll issue.

I'm not sure that installing Visual C++ (what version?) installs the VS redistributable that is needed. You need **exactly** the linked VS redistributable (2013 x86).

Another user managed to fix it in a weird way in #27 (but I can't recommend that).

**Comment by alfeh** [comment]
Alright I've downloaded and installed the file you linked but I still get the exact same issue as before. 
I had a quick read through that other fix in #27 but I'm a bit hesitant to download windows .dll's off of a website, but maybe I'll give it a go once I read a bit more into exactly what that file is and why it had to be re-downloaded.

**Comment by bugdone** [comment]
A quick google search gets me to [this](http://answers.microsoft.com/en-us/windows/forum/all/how-do-i-fix-missing-msvcp110dll-file/cc465e15-4cff-48bc-82bb-b8b8ac30fe8f) which suggests that the dll mentioned in #27 (msvcp110.dll) is available in Visual C++ Redistributable for Visual Studio 2012 Update 4

**Comment by bugdone** [comment]
Try the latest version. Should not require VS redistributable anymore.

**Comment by bugdone** [comment]
Closing due to lack of feedback.
