### ISSUE TITLE
Rank size too big

### ISSUE THREAD

**Issue by avqo** [bugdone/headshotbox#105]
Well I updated to 0.11.0 and this has happened to the ranks.

![](http://i.imgur.com/jCFcWwM.jpg)
![](http://i.imgur.com/w6H3CRv.jpg)

I've tried deleting my local files and going back to 0.10.0 and it still didn't fix it.

**Comment by bugdone** [comment]
browser name and version?
I'm assuming clearing the cache / restarting the browser would fix it (if you switched to 0.10).

**Comment by avqo** [comment]
Google Chrome Version 47.0.2526.106 m (64-bit)

**Comment by zergl64** [comment]
Had the issue with latest Firefox, clearing cache and restarting helped.

**Comment by avqo** [comment]
Can confirm that clearing cache seems to have fixed it.

**Comment by bugdone** [comment]
Did the rank pictures got fixed for 0.11 or 0.10 after wiping cache?

**Comment by avqo** [comment]
Well, I think I could've just cleared my cache, but I did this:

Cleared Cache
Deleted all HeadshotBox files
Download 0.10.0 (let it find all the demo stuff)
Upgrade to 0.11.0

**Comment by bugdone** [comment]
It's the cache. The picture files got updated, but the html files were cached from 0.10.
