### ISSUE TITLE
changing date range breaks round win % map names

### ISSUE THREAD

**Issue by zvans18** [bugdone/headshotbox#107]
http://i.imgur.com/Gnh27ip.png (note: the hover over names are the correct ones)
the lower label names revert to the correct ones if you delete the date range

hsb 0.11
java 8 u66
win 8.1 x64

**Comment by clugg** [comment]
Had this issue also, clearing my browser's cache fixed it.

**Comment by zvans18** [comment]
well clearing cache fixed my other issue (#106), but not this one

**Comment by clugg** [comment]
My mistake, was meaning to reply to #106 in another tab.

**Comment by pollyzoid** [comment]
I managed to reproduce this. Smallest case is two demos, one older and one newer. Putting the start date between them breaks Round Win% graph titles: https://i.imgur.com/qPzzsDv.png

Test case: hsbox 0.11, on Windows (I think linux works too), with these two demos: http://www.mediafire.com/download/l5ucz9dbij24orb/hsbox-round-bug.7z (40 MB).
Unpack demos, click player looz, go to Round Win %, set start date to Jan 01 2016.

**Comment by bugdone** [comment]
@pollyzoid: thanks for taking the time to get the minimal data that triggers the bug
