### ISSUE TITLE
headshotbox.bat closes when opened instantly

### ISSUE THREAD

**Issue by StrugglingXeno** [bugdone/headshotbox#111]

**Comment by bugdone** [comment]
Check out the log [see wiki](https://github.com/bugdone/headshotbox/wiki/Setup#files)

**Comment by epichalt** [comment]
I´ve got the same issue with windows 10. 
I start the bat and the Window is like for 0.5secs open and getting closed.

**Comment by epichalt** [comment]
ok i had no java it works now. despite i see no demos

**Comment by bugdone** [comment]
Did you set the demo directory?

**Comment by bugdone** [comment]
Closing due to lack of feedback.
