### ISSUE TITLE
Literally don't even know how to start it

### ISSUE THREAD

**Issue by Reddhero12** [bugdone/headshotbox#112]
I updated the player list with the .bat, went to the IP, everything was updated. Closed the .bat, closed the website, tried to open the .jar, and nothing happens. How do I run this?

**Comment by bugdone** [comment]
Did you read the [Setup wiki page](https://github.com/bugdone/headshotbox/wiki/Setup)?
The bat starts the application (which is a web service). If you close it, you close the application. The jar is used by the bat.

**Comment by bugdone** [comment]
Closing due to lack of feedback.
