### ISSUE TITLE
The requested operation requires elevation←[m

### ISSUE THREAD

**Issue by mpguidry** [bugdone/headshotbox#113]
←[37mjava.lang.Runtime.exec←[m  ←[32m                ←[m
←[37mjava.lang.ProcessBuilder.start←[m  ←[32m                ←[m
   ←[37mjava.lang.ProcessImpl.start←[m  ←[32m                ←[m
  ←[37mjava.lang.ProcessImpl.<init>←[m  ←[32m                ←[m
  ←[37mjava.lang.ProcessImpl.create←[m  ←[32m                ←[m
←[1;31mjava.io.IOException←[m: ←[3mCreateProcess error=740, The requested operat
ion requires elevation←[m
←[1;31mjava.io.IOException←[m: ←[3mCannot run program "D:\Desktop\headshotbox-0.
11.0-win/demoinfogo": CreateProcess error=740, The requested operation requires
elevation←[m

**Comment by mpguidry** [comment]
moved headshotbox from D:\Desktop\headshotbox-0.
11.0-win to C:\ and it works

**Comment by bugdone** [comment]
There's nothing I can do here.
What I gather from a quick google search is that either:
* there's weird ACL on those files
* you have UAC enabled

**Comment by mpguidry** [comment]
I figured it out. UAC is OFF, but my D:\ drive at one point was my old C:\, i plugged it in to recover files, deleted what i didnt need, and used it as my new data drive. Some old file permissions from old windows install is lingering around and randomly wreaking havoc. Quick format of the drive and it solved many issues i had.
