### ISSUE TITLE
Ranks not shown on demo overview

### ISSUE THREAD

**Issue by MSVilsen** [bugdone/headshotbox#115]
I am unable to see my ranks on the overview on my demos, however I am able to see the ranks once I open the scoreboard and also the rank next to my profile.

**Comment by clugg** [comment]
What version are you using? MM rank displaying in the player and demo lists was only added in 0.11. If you're up to date already, try clearing your browser's cache (CTRL+SHIFT+DEL) and doing a hard refresh (CTRL+F5).

**Comment by MSVilsen** [comment]
I'm using the newest version (0.11). I'll try clearing my cache and doing hard refresh. Thanks! :)

**Comment by MSVilsen** [comment]
Hello again. I've now tried both your suggestions, and sadly neither worked. I have attached a screenshot of my demo list.
![demos](https://cloud.githubusercontent.com/assets/16489216/12071434/bf1b4bea-b0ac-11e5-9b6e-37c3e9eaae60.png)

**Comment by bugdone** [comment]
This is actually how I designed it to work: the Rank column is displayed only if Valve demos are displayed. Otherwise the Type column replaces it. If you choose Valve in the Demo Type filter, you'll see the ranks.

I assume this UI is confusing.

**Comment by Haza** [comment]
Just an idea.

If we have more that one type of demo (Valve/FaceIt), couldn't we display both columns (ranks + Type) with an empty "Rank" when the type is differents that Valve ?

**Comment by bugdone** [comment]
Will do.

**Comment by Haza** [comment]
:+1: awsome, thanks for you work on this application !
