### ISSUE TITLE
Questions about contributions

### ISSUE THREAD

**Issue by mjseabright** [bugdone/headshotbox#118]
Hey bugdone,

Firstly, sorry for creating an issue for this but I didn't know how else to contact you.

Secondly, well done on headshotbox so far. It's a great tool.

I thought about making something similar to headshotbox a little while ago but it never got very far. However, I still have a lot of ideas for features that I think would be great additions to headshotbox. 

I would like to contribute to this project and possibly implement some of the ideas I have (with your approval of course). However, my problem is that I am an amateur programmer at best and have no experience with Clojure. Would you prefer that I do my best to learn Clojure and contribute what I can code wise or to just give you all my ideas so you can implement what you like? Keep in mind that any code I contribute is likely to be of low quality.

Thanks a lot and keep up the good work.

**Comment by bugdone** [comment]
Why not both?
Tell me your ideas. At the same time, if you enjoy programming, give Clojure a try. You might find it fun (especially if you didn't used a functional programming language before).

This is my first Clojure project so I assume the code is pretty bad.

If you want to shoot me an email: my gmail account has the same name as my github one.

Also check out [CSGO Demos Manager](https://github.com/akiver/CSGO-Demos-Manager). It's written in C#.
