### ISSUE TITLE
I lost 16-14, but it shows it as 17-13.

### ISSUE THREAD

**Issue by avqo** [bugdone/headshotbox#119]
This game that I played ended up very close at 16-14, but on HeadshotBox, it shows it as 17-13 for some peculiar reason. The first half score is right, the second half isn't. I can provide the demo if necessary.
![](https://i.imgur.com/iNkdSCe.png)

**Comment by bugdone** [comment]
Please send me the demo

**Comment by avqo** [comment]
@bugdone Here you go: https://www.mediafire.com/?fkh6qam836r0fpr

**Comment by avqo** [comment]
@bugdone Any clue what it could be? Could you replicate this too with my demo?

**Comment by bugdone** [comment]
It's a bug in the heuristic I used to fix #60 
I'll fix this, but the stats won't be 100% correct as the demo is missing some events (eg. Juni0r's death in round 25)

**Comment by avqo** [comment]
Okay, sounds good.
