### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by cmschaltz** [bugdone/headshotbox#121]
Hello Greate program :+1: 

Is it possible to make a launch option, that will remove the settings from the index.html page ? 

like java -jar hsbox-0.11.0-standalone.jar --port 4000 --nosettings 

or something like that.

/Chris

**Comment by bugdone** [comment]
You could set it so only a certain logged-in steamid can access the settings ([wiki](https://github.com/bugdone/headshotbox/wiki/Setup#steam-openid))

**Comment by cmschaltz** [comment]
Sweet thanks :D
