### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by evil-genius9000** [bugdone/headshotbox#122]
Parsing the demos fails with the following error:
java.io.IOException: error=13, Permission denied
java.io.IOException: Cannot run program "/home/james/temp/headshotbox-0.11.0-linux/headshotbox-0.11.0-linux/demoinfogo": error=13, Permission denied

**Comment by bugdone** [comment]
Try to manually run demoinfogo on a demo.

**Comment by evil-genius9000** [comment]
Setting execute permissions on demoinfogo fixed the problem. I had set headshotbox.sh to be executable but had not realised that demoinfogo required them too.
