### ISSUE TITLE
Chat log parsing

### ISSUE THREAD

**Issue by wizpig64** [bugdone/headshotbox#127]
If possible, it would be cool to see the chat logs from each match. It's in the demo files but I have no idea if its extractable. My friend showed me some dota 2 tracking services that generate a word cloud too, which is kind of interesting.

**Comment by bugdone** [comment]
In MM demos the chat is missing.

**Comment by wizpig64** [comment]
It shows in the console

**Comment by bugdone** [comment]
Honestly I think this feature is so low priority that I'm never going to do it. So I'll just go ahead and close it now.

**Comment by wizpig64** [comment]
kk, thanks for making headshotbox
