### ISSUE TITLE
Add support for FreeBSD

### ISSUE THREAD

**Issue by mpguidry** [bugdone/headshotbox#129]
When trying to run on bsd I get an error - 

java.lang.Exception: Error loading native library: /org/sqlite/native/FreeBSD/amd64/libsqlitejdbc.so
java.sql.SQLException: Error opening connection
    errorCode: 0

I unpacked the jar and inside /org/SQLite/native/ there is no FreeBSD folder.

Could you add the libs in please?

**Comment by bugdone** [comment]
Is the demoinfogo binary running on FreeBSD?

**Comment by mpguidry** [comment]
Im not sure what you mean, but im just running headshot box like I did on windows by running the jar. Here is the output of it starting up

``root@headshotbox:/usr/local/share/headshotbox # ./headshotbox.sh
2016-Feb-24 09:29:14 -0600 headshotbox INFO [hsbox.core] - HeadshotBox 0.11.0
2016-Feb-24 09:29:14 -0600 headshotbox INFO [hsbox.version] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
Feb 24, 2016 9:29:15 AM org.openid4java.server.RealmVerifier setEnforceRpId
WARNING: RP discovery / realm validation disabled;
Feb 24, 2016 9:29:15 AM org.openid4java.consumer.ConsumerManager setMaxAssocAttempts
INFO: Associations disabled.
2016-02-24 09:29:15.193:INFO:oejs.Server:jetty-7.x.y-SNAPSHOT
2016-02-24 09:29:15.369:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4000
2016-Feb-24 09:29:15 -0600 headshotbox ERROR [hsbox.core] -
                                    hsbox.core.main
                                                ...
                                   hsbox.core/-main               core.clj:  56
                         hsbox.db/init-db-if-absent                 db.clj:  59
                                   hsbox.db/init-db                 db.clj:  48
                                                ...
                             hsbox.db/exec-sql-file                 db.clj:  45
                                 clojure.core/apply               core.clj: 628
                                                ...
                   clojure.java.jdbc/db-do-commands               jdbc.clj: 680
                   clojure.java.jdbc/get-connection               jdbc.clj: 255
               java.sql.DriverManager.getConnection     DriverManager.java: 208
               java.sql.DriverManager.getConnection     DriverManager.java: 664
                            org.sqlite.JDBC.connect              JDBC.java:  88
                   org.sqlite.JDBC.createConnection              JDBC.java: 114
                 org.sqlite.SQLiteConnection.<init>  SQLiteConnection.java:  45
            org.sqlite.jdbc4.JDBC4Connection.<init>   JDBC4Connection.java:  23
            org.sqlite.jdbc3.JDBC3Connection.<init>   JDBC3Connection.java:  21
              org.sqlite.core.CoreConnection.<init>    CoreConnection.java:  66
                org.sqlite.core.CoreConnection.open    CoreConnection.java: 136
                      org.sqlite.core.NativeDB.load          NativeDB.java:  53
             org.sqlite.SQLiteJDBCLoader.initialize  SQLiteJDBCLoader.java:  65
org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary  SQLiteJDBCLoader.java: 243
  java.lang.Exception: Error loading native library: /org/sqlite/native/FreeBSD/amd64/libsqlitejdbc.so
java.sql.SQLException: Error opening connection
    errorCode: 0

2016-Feb-24 09:29:15 -0600 headshotbox DEBUG [hsbox.version] - Latest version 0.11.0
``

**Comment by bugdone** [comment]
Just run the demoinfogo binary from the same directory and see if any errors are yielded.

**Comment by mpguidry** [comment]
root@headshotbox:/usr/local/share/headshotbox # ./demoinfogo
ELF binary type "3" not known.
./demoinfogo: Exec format error. Binary file not executable.
root@headshotbox:/usr/local/share/headshotbox #

**Comment by bugdone** [comment]
As mentioned in #98, there are two binaries in Headshot Box.
The sqlite problem can be solved by just updating the sqlite dependency version in project.clj (since newer sqlite jars contain the FreeBSD and ARM binaries)
But you still need to compile [demoinfogo](https://github.com/bugdone/demoinfogo-linux) for FreeBSD.

**Comment by mpguidry** [comment]
guess ive got some googling to do. thanks.
