### ISSUE TITLE
Demo is not added, when player had left before match started

### ISSUE THREAD

**Issue by WuaghhhhXMA** [bugdone/headshotbox#13]
I have a demo file, where we had to play with a bot, because teammate had the vac-authentification error in warmup and could not reconnect on time. Now the demo cannot be added, because the player count is less 10.

PS: I can understand that those kind of bugs may not be handled prioritized. ;)

**Comment by abenea** [comment]
Can you please upload the dem file somewhere so we can take a look?

**Comment by WuaghhhhXMA** [comment]
http://www12.zippyshare.com/v/NHc5BBpl/file.html

**Comment by abenea** [comment]
Thank you, this will be fixed in 0.5
