### ISSUE TITLE
Add ADR to individual Demo stats, or allow customization of fields for each demo

### ISSUE THREAD

**Issue by avm83** [bugdone/headshotbox#131]
Feature request to add another column to individual demo stats table

**Comment by hAnnahf** [comment]
I would appreciate this one as well.

**Comment by bugdone** [comment]
Are you referring to the stats in the demo list (the one with the watch buttons) or the scoreboard of a demo?

**Comment by avm83** [comment]
Well, it'd be kinda nice to have it in both, but I guess my initial request was to show every player's ADR in the Demo Scoreboards.

Also, as someone who doesn't really use Demo Notes, it seems like a lot of scoreboard real estate(for more columns of stats) is lost having the notes on the right side of the demo scoreboard.  Maybe it could go under the scoreboard?

Just brain-storming... I love headshot box even as it is, and I'm constantly telling others what an awesome tool this is!

**Comment by bugdone** [comment]
I have grown to hate the placement of the notes as well. Probably 99% of the demos don't have notes anyway.
