### ISSUE TITLE
The Watch button never works for me

### ISSUE THREAD

**Issue by hAnnahf** [bugdone/headshotbox#132]
The Watch button doesn't work anywhere in HeadshotBox. I'm running the latest version (0.11.0). The csgo.exe process doesn't even start after clicking the button. Lowlights and highlights buttons don't do anything either. Neither do the buttons for concrete rounds / game events.

I suppose there must be something wrong about the path. Here is a Watch button link from a random demo:
`steam://rungame/730/76561198025125345/+playdemo "E:%5CSteam%5CSteamApps%5Ccommon%5CCounter-Strike%20Global%20Offensive%5Ccsgo%5Creplays%5Cmatch730_003130286810886832290_1352100132_191.dem"`

Thanks in advance for looking into this. Also, thanks for developing such a neat tool. :)

**Comment by bugdone** [comment]
Do the "Inspect in Game..." buttons from Community Market work for you?

**Comment by hAnnahf** [comment]
Thanks for pushing me into right direction! Sure, the inspect links didn't work either so I realized it's a problem with Chrome protocol handlers. In Firefox everything worked smoothly. So I fixed it using this [tutorial](http://superuser.com/a/451490).

**Comment by hAnnahf** [comment]
Thanks for pushing me into right direction! Sure, the inspect links didn't work either so I realized it's a problem with Chrome protocol handlers. In Firefox everything worked smoothly. So I fixed it using this [tutorial](http://superuser.com/a/451490).
