### ISSUE TITLE
Watch Demo problem

### ISSUE THREAD

**Issue by minimalis91** [bugdone/headshotbox#145]
I have a folder named 'demos' in the program directory and this folder is selected as 'Demo directory' in the settings.
However I also have multiple folders inside the demo directory for each steam account. It is more organised this way. However when I use the Watch demo button the command skips the sub-folder and uses the demo directory as the path/location for all demos.

For example: 
I want to watch a demo of my main account.
The correct location of the demo is: "C:\HSBox\demos\main\xxxx.dem" (This is not the actual location, just an example but I don't think it matters?)
While the Watch button links to the following: "steam://rungame/730/[steamid]/+playdemo "C:%5CHSBox%5Cdemos%5Cxxxx.dem"
This only starts the game because there are no dem files in the demo folder.

It can correctly parse demos from the sub-dirs but tries to run every demo as if they were in the main dir.
I am using 0.11.0 for windows.

**Comment by bugdone** [comment]
I assumed when I wrote the code that people won't use subdirectories :)
I am curious, how does it help having separate folders for different accounts?

**Comment by minimalis91** [comment]
If we are only talking about this program it does not help as the program does the sorting for you.

But it is good to know which dem file belongs to which account outside of the program. 
File names like "match730_003038430405456822424_1565398199_135.dem" does not really talk much in that sense.
Maybe if I were to use the demos with a different program in the future or something like that.
Or maybe I just have a mild case of OCD and I like everything organized. :)

My replay folder is already over 10 gigabytes so I will know which demos to delete right away when I will have to free up some space.

It is not a program breaking bug though. I just figured I would tell you.

**Comment by bugdone** [comment]
Thanks for letting me know.
I never used subdirectories and not one user mentioned this bug in almost a year now :)
