### ISSUE TITLE
3massert failed

### ISSUE THREAD

**Issue by madtoad14** [bugdone/headshotbox#148]
2 out of my 19 ESEA pug demos seem to not be parsed, it just gives me these msgs. http://puu.sh/nVemn/86eb10d88f.png
Every time the program gets to the demos that dont work, the program starts 'not responding', i click the error box away and it will continue going through the rest of the demos. I don't know if i explained the problem well enough, anything i can do?
these are the 2 demos causing issues:
http://www.speedyshare.com/73yWk/esea-match-6397584.dem
http://www.speedyshare.com/hDBwt/esea-match-6367865.dem

I have done what the FAQ tells me to -> https://github.com/bugdone/headshotbox/wiki/FAQ#log-mentions-exception-in-thread-main-javalangassertionerror-assert-failed-zero-exit-proc

**Comment by bugdone** [comment]
Both demos are corrupted. When playdemo gets to the last round, the playback stops (sometimes CSGO crashes as well).

**Comment by bugdone** [comment]
I'll fix the crash so it won't pop the 'not responding' window, but it won't parse the demo.
