### ISSUE TITLE
Demos not parsing on Ubuntu 

### ISSUE THREAD

**Issue by mpguidry** [bugdone/headshotbox#153]
Downloaded the latest linux build. Trying to run on an ubuntu container.  Checked log file and it's says '/usr/local/share/headshot/demoinfogo' demoinfogo not found. It is in fact in the right directory. I'm deff lost on this one.

**Comment by bugdone** [comment]
How are you starting hsbox? Where did you unpack the files, what command are you running and from what directory?

**Comment by mpguidry** [comment]
I have tried it from /usr/local/share/headshot,  also tried from /, and ~/. I have tried to run it with nohup ./headshotbox.sh &, I also tried just ./headshotbox.sh both give the same result.

**Comment by mpguidry** [comment]
Oops /headshot and ~/headshot

**Comment by bugdone** [comment]
I have no clue what's going on.
Can you run demoinfogo?

**Comment by mpguidry** [comment]
just tried the demoinfogo  that comes with your latest release, and it wont run. 

`^[[1;31mjava.io.IOException^[[m: ^[[3mCannot run program "/root/headshotbox/demoinfogo": error=2, No such file or directory^[[m`

also tried to build demoinfogo and it fails to build.

**Comment by bugdone** [comment]
That error is issued by headshotbox when it tries to run demoinfogo.
Run demoinfogo manually (ie. type `/usr/local/share/headshotbox/demoinfogo` into the console). You should see the program's usage.

**Comment by bugdone** [comment]
closing due to lack of feedback

**Comment by loliday1337** [comment]
Has same issue on Ubuntu
![image](https://user-images.githubusercontent.com/47452991/52484361-2b82f600-2bc7-11e9-85bd-98b557a6f8e0.png)

**Comment by l00z** [comment]
I encountered this same issue, fixed it by pulling dependencies of [demoinfogo-linux](https://github.com/xiris/demoinfogo-linux). Was probably missing glibc.
