### ISSUE TITLE
OpenID Realm Question.

### ISSUE THREAD

**Issue by Rsslone** [bugdone/headshotbox#155]
Sorry If this is posted in the wrong area, I looked for contact information but could not find.

I have a question about OpenID and realms. Do you need to have a site to use this feature or can this be used Localhost? If I can use it localhost do you need a plugin for apache and have Headshotbox running within apache instead of the .bat? I want to share the server with our team memebers but I don't want to hand out my steam API key. **It would be nice to move the steam API key and replay directory to a config file instead.**

Thanks.

**Comment by bugdone** [comment]
You only want to use the OpenID feature if you want other people to use it.
In this case, you probably have a dns name or Ip for your machine that the people use to connect to your machine. Use this as a realm.

**Comment by Rsslone** [comment]
I am using 
"java -jar hsbox-0.11.0-standalone.jar --port 4000 --admin-steamid 76xxxxxxxxxxxx042 --openid-realm 68.x.xx.x23"

It returns a blank page at http://127.0.0.1:4000/openid

**Comment by bugdone** [comment]
The openid-realm must be the url used by your users.
If your ip is 68.x.xx.x23 and your port 4000, use `--openid-realm http://68.x.xx.x23:4000/`.

**Comment by Rsslone** [comment]
Still returns a blank page. http://puu.sh/oXw6R/cbdb87864b.png

I am using 

java -jar hsbox-0.11.0-standalone.jar --port 4000 --admin-steamid 76xxxxxxxxxxxxx42 --openid-realm http://68.x.xx.xx3:4000/

**Comment by Rsslone** [comment]
Here is a console log if this helps.

S:\MEGAsync\Software\headshotbox-0.11.0-win>java -jar hsbox-0.11.0-standalone.ja
r --port 4000 --admin-steamid 76xxxxxxxxxxxxx42 --openid-realm http://68.x.xx.xx
3:4000/
2016-May-19 05:38:01 -0700 Slone-PC INFO [hsbox.core] - HeadshotBox 0.11.0
2016-May-19 05:38:01 -0700 Slone-PC INFO [hsbox.version] - Checking latest versi
on on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-window
s-version
May 19, 2016 5:38:01 AM org.openid4java.server.RealmVerifier setEnforceRpId
WARNING: RP discovery / realm validation disabled;
May 19, 2016 5:38:01 AM org.openid4java.consumer.ConsumerManager setMaxAssocAtte
mpts
INFO: Associations disabled.
2016-05-19 05:38:01.985:INFO:oejs.Server:jetty-7.x.y-SNAPSHOT
2016-05-19 05:38:02.057:INFO:oejs.AbstractConnector:Started SelectChannelConnect
or@0.0.0.0:4000
2016-May-19 05:38:02 -0700 Slone-PC DEBUG [hsbox.version] - Latest version 0.11.
0
2016-May-19 05:38:02 -0700 Slone-PC DEBUG [hsbox.indexer] - Indexer started
May 19, 2016 5:38:14 AM org.openid4java.discovery.Discovery discover
INFO: Starting discovery on URL identifier: http://steamcommunity.com/openid
May 19, 2016 5:38:15 AM org.openid4java.discovery.yadis.YadisResolver discover
INFO: Yadis discovered 1 endpoints from: http://steamcommunity.com/openid
May 19, 2016 5:38:15 AM org.openid4java.discovery.Discovery discover
INFO: Discovered 1 OpenID endpoints.
May 19, 2016 5:38:15 AM org.openid4java.consumer.ConsumerManager associate
WARNING: Association failed; using first entry: https://steamcommunity.com/openi
d/login
May 19, 2016 5:38:15 AM org.openid4java.consumer.ConsumerManager authenticate
INFO: Creating authentication request for OP-endpoint: https://steamcommunity.co
m/openid/login claimedID: http://specs.openid.net/auth/2.0/identifier_select OP-
specific ID: http://specs.openid.net/auth/2.0/identifier_select
May 19, 2016 5:38:15 AM org.openid4java.server.RealmVerifier validate
SEVERE: Return URL: http://127.0.0.1:4000/openid does not match realm: http://68
.2.58.223:4000/
2016-May-19 05:38:15 -0700 Slone-PC ERROR [hsbox.handler] -
                                                                     ←[37mjava.l
ang.Thread.run←[m  ←[32m                                 ←[m
                                     ←[37morg.eclipse.jetty.util.thread.QueuedTh
readPool$3.run←[m  ←[32m      QueuedThreadPool.java:  543←[m
                                    ←[37morg.eclipse.jetty.util.thread.QueuedThr
eadPool.runJob←[m  ←[32m      QueuedThreadPool.java:  608←[m
                                     ←[37morg.eclipse.jetty.io.nio.SelectChannel
EndPoint$1.run←[m  ←[32m SelectChannelEndPoint.java:   52←[m
                                    ←[37morg.eclipse.jetty.io.nio.SelectChannelE
ndPoint.handle←[m  ←[32m SelectChannelEndPoint.java:  668←[m
                                      ←[37morg.eclipse.jetty.server.AsyncHttpCon
nection.handle←[m  ←[32m   AsyncHttpConnection.java:   82←[m
                                         ←[37morg.eclipse.jetty.http.HttpParser.
parseAvailable←[m  ←[32m            HttpParser.java:  240←[m
                                              ←[37morg.eclipse.jetty.http.HttpPa
rser.parseNext←[m  ←[32m            HttpParser.java:  865←[m
                   ←[37morg.eclipse.jetty.server.AbstractHttpConnection$RequestH
andler.content←[m  ←[32mAbstractHttpConnection.java: 1005←[m
                                  ←[37morg.eclipse.jetty.server.AbstractHttpConn
ection.content←[m  ←[32mAbstractHttpConnection.java:  944←[m
                            ←[37morg.eclipse.jetty.server.AbstractHttpConnection
.handleRequest←[m  ←[32mAbstractHttpConnection.java:  486←[m
                                                   ←[37morg.eclipse.jetty.server
.Server.handle←[m  ←[32m                Server.java:  369←[m
                                   ←[37morg.eclipse.jetty.server.handler.Handler
Wrapper.handle←[m  ←[32m        HandlerWrapper.java:  116←[m
←[37mring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$f
f19274a.handle←[m  ←[32m                                 ←[m
                                                      ←[33mring.adapter.jetty/pr
oxy-handler/←[1;33mfn←[m  ←[32m                  jetty.clj:   20←[m
                                                  ←[33mring.middleware.session/w
rap-session/←[1;33mfn←[m  ←[32m                session.clj:   98←[m
                                                      ←[33mring.middleware.flash
/wrap-flash/←[1;33mfn←[m  ←[32m                  flash.clj:   35←[m
                                ←[33mring.middleware.multipart-params/wrap-multi
part-params/←[1;33mfn←[m  ←[32m       multipart_params.clj:  118←[m
                                                    ←[33mring.middleware.params/
wrap-params/←[1;33mfn←[m  ←[32m                 params.clj:   64←[m
                                      ←[33mring.middleware.nested-params/wrap-ne
sted-params/←[1;33mfn←[m  ←[32m          nested_params.clj:   84←[m
                                    ←[33mring.middleware.keyword-params/wrap-key
word-params/←[1;33mfn←[m  ←[32m         keyword_params.clj:   35←[m
                                                          ←[33mhsbox.handler/wra
p-exception/←[1;33mfn←[m  ←[32m                handler.clj:  132←[m
                                                          ←[33mcemerick.friend/a
uthenticate/←[1;33mfn←[m  ←[32m                 friend.clj:  260←[m
                                                            ←[33mcemerick.friend
/←[1;33mauthenticate*←[m  ←[32m                 friend.clj:  247←[m
                                                     ←[33mcemerick.friend/←[1;33
mauthenticate-request←[m  ←[32m                 friend.clj:  238←[m
                                                                        ←[33mclo
jure.core/←[1;33msome←[m  ←[32m                   core.clj: 2515←[m
                                                  ←[33mcemerick.friend/authentic
ate-request/←[1;33mfn←[m  ←[32m                 friend.clj:  238←[m
                                                       ←[33mcemerick.friend.open
id/workflow/←[1;33mfn←[m  ←[32m                 openid.clj:  118←[m
                                                       ←[33mcemerick.friend.open
id/←[1;33mhandle-init←[m  ←[32m                 openid.clj:   54←[m

      ←[37m...←[m  ←[32m                                 ←[m
                                    ←[37morg.openid4java.consumer.ConsumerManage
r.authenticate←[m  ←[32m       ConsumerManager.java: 1071←[m
                                    ←[37morg.openid4java.message.AuthRequest.cre
ateAuthRequest←[m  ←[32m           AuthRequest.java:  101←[m
                                             ←[37morg.openid4java.message.AuthRe
quest.validate←[m  ←[32m           AuthRequest.java:  354←[m
←[1;31morg.openid4java.message.MessageException←[m: ←[3m0x301: Realm verificatio
n failed (8) for: http://68.x.xx.xx3:4000/←[m
    ←[1merrorCode←[m: 769

2016-05-19 05:38:15.079:WARN:oejs.AbstractHttpConnection:/openid
org.openid4java.message.MessageException: 0x301: Realm verification failed (8) f
or: http://68.x.xx.x23:4000/
        at org.openid4java.message.AuthRequest.validate(AuthRequest.java:354)
        at org.openid4java.message.AuthRequest.createAuthRequest(AuthRequest.jav
a:101)
        at org.openid4java.consumer.ConsumerManager.authenticate(ConsumerManager
.java:1071)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at cemerick.friend.openid$handle_init.invoke(openid.clj:54)
        at cemerick.friend.openid$workflow$fn__9452.invoke(openid.clj:118)
        at cemerick.friend$authenticate_request$fn__9003.invoke(friend.clj:238)
        at clojure.core$some.invoke(core.clj:2515)
        at cemerick.friend$authenticate_request.invoke(friend.clj:238)
        at cemerick.friend$authenticate_STAR_.invoke(friend.clj:247)
        at cemerick.friend$authenticate$fn__9013.invoke(friend.clj:260)
        at hsbox.handler$wrap_exception$fn__9557.invoke(handler.clj:132)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__1519.invoke(ke
yword_params.clj:35)
        at ring.middleware.nested_params$wrap_nested_params$fn__1562.invoke(nest
ed_params.clj:84)
        at ring.middleware.params$wrap_params$fn__1492.invoke(params.clj:64)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__1598.invok
e(multipart_params.clj:118)
        at ring.middleware.flash$wrap_flash$fn__2272.invoke(flash.clj:35)
        at ring.middleware.session$wrap_session$fn__2259.invoke(session.clj:98)
        at ring.adapter.jetty$proxy_handler$fn__9641.invoke(jetty.clj:20)
        at ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHan
dler$ff19274a.handle(Unknown Source)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper
.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:369)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(Abstrac
tHttpConnection.java:486)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpC
onnection.java:944)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.conten
t(AbstractHttpConnection.java:1005)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)

        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnecti
on.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEn
dPoint.java:668)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEnd
Point.java:52)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPoo
l.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool
.java:543)
        at java.lang.Thread.run(Unknown Source)

**Comment by bugdone** [comment]
Use the public IP in your browser, not 127.0.0.1
If you browse the server using http://127.0.0.1:4000, then the domain name won't match the url and OpenID won't work.

**Comment by Rsslone** [comment]
Brilliant. I owe you a up of coffee. You have donate link?

**Comment by bugdone** [comment]
No mate, I do it for the love. :neckbeard:
If you like the software, tell others about it.

**Comment by Rsslone** [comment]
Well I super appreciate your help! Thanks for the tool awesome tool!
