### ISSUE TITLE
New version doesn't work

### ISSUE THREAD

**Issue by kittykiller** [bugdone/headshotbox#156]
When I attempted to view my demos on the web I get this error.
http://pastebin.com/3m27V5TX

**Comment by bugdone** [comment]
Can you give me the full log since you installed the new version?

**Comment by kittykiller** [comment]
There is also a screenshot that doesn't show up in the log but shows up in the console.
https://dl.dropboxusercontent.com/u/664153/Headshot.7z

**Comment by bugdone** [comment]
In that screenshot it looks like it might be running the JS old code. Did you clear the cache / restart the browser?

**Comment by kittykiller** [comment]
I did, also tried using a different browser and still the same result.

**Comment by bugdone** [comment]
Can you look at the http requests made by the "Player List" page (using the debug tools in your browser)?
Should be something like: http://localhost:4000/api/players?limit=50&offset=0

**Comment by kittykiller** [comment]
![screenshot 2016-05-25 17 37 55](https://cloud.githubusercontent.com/assets/4710935/15555641/ff4612c6-229f-11e6-83d7-b9185182f1b7.png)
![screenshot 2016-05-25 17 40 43](https://cloud.githubusercontent.com/assets/4710935/15555642/ff50f808-229f-11e6-9e4b-8399afae9154.png)

I can get to the player list fine it's just when I click on my name to get the demos.

**Comment by bugdone** [comment]
Can you send me the headshotbox.sqlite file?

**Comment by kittykiller** [comment]
[headshotbox.zip](https://github.com/bugdone/headshotbox/files/282965/headshotbox.zip)

**Comment by bugdone** [comment]
Thanks, I found the bug. I'll work on the fix tomorrow.

As a workaround, I think that it might work if you set the replays dir to "/C:/Program Files (x86)/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/replays/".

**Comment by bugdone** [comment]
This bug is hard to reproduce.
Try [this build](https://drive.google.com/open?id=0By1S9k1ZbkWDWll2b1JlSnhqdms). Just delete headshotbox.sqlite and it should work.

**Comment by kittykiller** [comment]
seems to work.
Another thing I noticed is that every time I launch the program it rescans every demo while before it only scanned new demos.

**Comment by dasinking** [comment]
Can confirm the rescan issue. Also have another problem: After the scanning is complete headshotbox crashes when clicking on a player name. (log: http://pastebin.com/48Hq7DNp)

**Comment by Janzert** [comment]
The 0.12.1 version posted above fixes the "relative path" exception, but not the rescan on every start, for me as well.

**Comment by bugdone** [comment]
[New build](https://drive.google.com/file/d/0By1S9k1ZbkWDUGxjSnhha3RNTG8/view?usp=sharing)
This should fix all the bugs posted here.

**Comment by dasinking** [comment]
Yep, works again. Just had to rebuild the database.

**Comment by bugdone** [comment]
It should have migrated the database so that the paths are correct and no manual changes would be required. Can I have the log from this build?

**Comment by dasinking** [comment]
It tried to, but crashed. http://pastebin.com/FirMxqpv

**Comment by bugdone** [comment]
Thanks, it looks like I messed up the migration code.

**Comment by dasinking** [comment]
Also, but I'm not entirely sure whether or not this is HSBox' fault, when I click on watch it just opens up my game, but not the demo.

**Comment by bugdone** [comment]
Please send me a copy of the console contents when this happens.

**Comment by dasinking** [comment]
It doesn't post anything into the console...

**Comment by bugdone** [comment]
Just post the full console log. It must be something about demos there. (it's not necessarily the last line).

**Comment by dasinking** [comment]
There my full log. http://pastebin.com/JP3jC4Zv

**Comment by bugdone** [comment]
I meant the CSGO console contents after you click on a watch button and it launches the game but not the demo.

**Comment by dasinking** [comment]
Oh, oops.

> Executing
> deferred playdemo: D:\Program
>CDemoFile::Open: couldn't open file D:\Program.dem for reading.

**Comment by bugdone** [comment]
Was this working before 0.12?
