### ISSUE TITLE
Can not view list of demos - dividing by zero (with ESEA demos)

### ISSUE THREAD

**Issue by Techtony96** [bugdone/headshotbox#16]
When trying to view a list of my demos I get an Arithmetic Exception, can not divide by zero.

Full stack trace [here](https://gist.github.com/Techtony96/5a277559f4f82197c30b)

**Comment by bugdone** [comment]
Do you happen to have by any chance ESEA demos in that directory?

**Comment by Techtony96** [comment]
yup, that was it. I removed the ESEA demos and it worked perfectly.
