### ISSUE TITLE
Feature request: Force Headshotbox to update steamid data

### ISSUE THREAD

**Issue by V0V4N** [bugdone/headshotbox#162]
It would be nice if you add a button to get fresh steamid data (vac/overwatch bans of players that u have demo with and some other stuff). Is it possible?

**Comment by bugdone** [comment]
For all players, or just for the list of players in a match (like [suggested here](https://github.com/bugdone/headshotbox/issues/57#issuecomment-111709948))?

**Comment by V0V4N** [comment]
Depends on how it affect stability of headshotbox. If it's possible to refresh about 2k steamid's by one button it would be fine when the button affects all players.

**Comment by bugdone** [comment]
I could do that but seems rather pointless. Steam data is refreshed every 24 hours. I don't see the point in checking it more often. Also, if you haven't run HeadshotBox in a couple of days, the data would be refreshed at startup.

**Comment by clugg** [comment]
I wrote a very basic Python script (>= 2.5) that does exactly this.

```python
import sqlite3
conn = sqlite3.connect("headshotbox.sqlite")
cur = conn.cursor()
cur.execute("UPDATE steamids SET timestamp='0'")
conn.commit()
conn.close()```

Put it in whatever directory headshotbox.sqlite is stored in (%USERPROFILE%/.config/headshotbox/ for Windows). Whenever you want to run it, close headshotbox first, run the script, then reopen it. Any games you view will instantly have all Steam data updated for involved players, or if you wait about 2 minutes it will automatically fetch new data for every player it knows of.
For me it fetches over 2.2k steamIDs at once without a hitch.
