### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Flazje** [bugdone/headshotbox#164]
Hello

I got this issue, any idea how to solve? http://i.imgur.com/swAC9y1.png

Been a long time user, worked good until update to 0.12 started having problems then. Folder from demos is okay.

King Regards

**Comment by clugg** [comment]
Somehow it has loaded the same demo twice against the database's constraint that every demo path must be unique. You will probably have to delete `headshotbox.sqlite` and let it parse all your demos again to fix it.

**Comment by bugdone** [comment]
It looks like a bug in the migration script. It would help if you could send me the headshotbox.sqlite file.
What @clugg says is correct: deleting the file would force a full rescan of all demos and you won't ever see that error (but it would lose the demo notes if you had any).

**Comment by yoyosan** [comment]
@bugdone maybe there should be a way to refresh the database without losing user notes?
