### ISSUE TITLE
Not loading demo playback.

### ISSUE THREAD

**Issue by singularentity** [bugdone/headshotbox#167]
When clicking on any demo related link it doesn't load into the demo.

console output for a 5k highlight. http://pastebin.com/SGQHt0T3
console output for a full demo http://pastebin.com/CHS7Xh6h
If anything else is needed let me know.
Cheers.

**Comment by bugdone** [comment]
Can you look in the Network inspector in the browser and tell me what the response is to the 
`http://127.0.0.1:4000/api/demo/<demoid>/watch` call is?

**Comment by singularentity** [comment]
I hope I'm looking at the right thing, after clicking the watch demo button under network there is two options. One for watch with returns a 200 status and one for +playdemo "D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\csgo\replays\match730_003149690242622030074_0256102082_171.dem@0" which returns a (cancelled) with no response listed.
I don't know if its important but in the console it appears to be stripping the folder path at the space between Counter-Strike and Global.

**Comment by bugdone** [comment]
I can reproduce the bug in Chrome, but in Firefox it works.
