### ISSUE TITLE
Cannot use the "Watch Round" Button on filtered rounds page

### ISSUE THREAD

**Issue by kikyou2** [bugdone/headshotbox#17]
If I try nothing happens

Okay, it only works if the game is closed and not if its running. Don't know if you can do anything about this.

**Comment by Hydrox6** [comment]
It is possible to open a demo whilst the game is running. IIRC, you can use a different command than steam://rungame to get that working. I would submit a PR, but I'm not in an environment to do so (nor to test it).

**Comment by yoyosan** [comment]
@Hydrox6 if you use either of those a "Failed to start game(app already running)" message will pop.

**Comment by Hydrox6** [comment]
@yoyosan any chance you could grab the link to watch someone's demo? It's at the bottom of the scoreboard. IIRC that link works even if CSGO is open, so it would be useful to see the format.

**Comment by yoyosan** [comment]
```
steam://rungame/730/76561197991140697/+playdemo "/home/yoyosan/.local/share/Steam/steamapps/common/Counter-Strike%20Global%20Offensive/csgo/replays/match730_003073446960288497763_0865371383_191.dem"
```

**Comment by yoyosan** [comment]
@Hydrox6 you're right. It works while running the game :)

**Comment by Hydrox6** [comment]
I think *csgo_download_match* works, but *playdemo* does not. Maybe, then, there's another way to play a demo from the steam protocol.

**Comment by bugdone** [comment]
I don't think there's a way to do this. I added an option to kill csgo before playdemo runs.
