### ISSUE TITLE
Banned players tab isn't filtered when filtering demo type/date/map etc

### ISSUE THREAD

**Issue by ajohnsen** [bugdone/headshotbox#176]
When filtering demos by date, the banned players list still show every banned person even if the demo of the banned player is filtered out.

**Comment by iFEARR** [comment]
Banned players doesn't even work for me

**Comment by bugdone** [comment]
check the logs. it might be that you can't reach steamapi

**Comment by iFEARR** [comment]
https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
2016-Aug-20 22:12:28 +0300 ** DEBUG [hsbox.version] - Latest version 0.15.2
2016-Aug-20 23:13:28 +0300 ** DEBUG [hsbox.indexer] - Adding path **\match730_003160471922647499083_0771343346_191.dem
2016-Aug-20 23:13:28 +0300 ** INFO [hsbox.demo] - Processing **\match730_003160471922647499083_0771343346_191.dem
2016-Aug-20 23:13:35 +0300 ** INFO [hsbox.demo] - Processing **\match730_003160471922647499083_0771343346_191.dem.info
2016-Aug-20 23:13:35 +0300 ** DEBUG [hsbox.db] - Adding demo data for **\match730_003160471922647499083_0771343346_191.dem
2016-Aug-20 23:13:41 +0300 ** DEBUG [hsbox.indexer] - Adding path **\match730_003160503018210721793_1556956570_192.dem
2016-Aug-20 23:13:41 +0300 ** INFO [hsbox.demo] - Processing **\match730_003160503018210721793_1556956570_192.dem
2016-Aug-20 23:13:50 +0300 ** INFO [hsbox.demo] - Processing **\match730_003160503018210721793_1556956570_192.dem.info
2016-Aug-20 23:13:50 +0300 ** DEBUG [hsbox.db] - Adding demo data for **\match730_003160503018210721793_1556956570_192.dem
2016-Aug-20 23:14:10 +0300 ** DEBUG [hsbox.steamapi] - Getting fresh data from the API for 9 steamids
2016-Aug-21 01:33:11 +0300 ** DEBUG [hsbox.indexer] - Adding path **\match730_003160518368423837701_0380499229_191.dem
2016-Aug-21 01:33:11 +0300 ** INFO [hsbox.demo] - Processing **\match730_003160518368423837701_0380499229_191.dem
2016-Aug-21 01:33:18 +0300 ** INFO [hsbox.demo] - Processing **\match730_003160518368423837701_0380499229_191.dem.info
2016-Aug-21 01:33:18 +0300 ** DEBUG [hsbox.db] - Adding demo data for **\match730_003160518368423837701_0380499229_191.dem
2016-Aug-21 01:33:28 +0300 ** DEBUG [hsbox.steamapi] - Getting fresh data from the API for 9 steamids
2016-Aug-21 03:55:31 +0300 ** DEBUG [hsbox.steamapi] - Getting fresh data from the API for 15 steamids
2016-Aug-21 03:55:31 +0300 ** DEBUG [hsbox.steamapi] - Getting fresh data from the API for 15 steamids
2016-Aug-21 15:34:56 +0300 ** DEBUG [hsbox.steamapi] - Getting fresh data from the API for 6 steamids

**Comment by bugdone** [comment]
There doesn't seem to be any problem reaching Steam API.
Was 2016-Aug-20 22:12:28 the first time you ran Headshotbox?

**Comment by iFEARR** [comment]
No, I had it for 2 weeks now.

I was looking in the log and I saw this.

`No, I had it for 2 weeks now.

I was looking in the log and I saw this.


2016-Aug-15 23:52:30 +0300 ** DEBUG [hsbox.version] - Latest version 0.15.2
2016-Aug-15 23:52:43 +0300 ** DEBUG [hsbox.indexer] - Indexer started
2016-Aug-15 23:53:48 +0300 ** INFO [hsbox.core] - HeadshotBox 0.15.2  
2016-Aug-15 23:53:48 +0300 ** INFO [hsbox.version] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
2016-Aug-15 23:53:51 +0300 ** ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  68[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2016-Aug-15 23:54:47 +0300 ** INFO [hsbox.core] - HeadshotBox 0.15.2  
2016-Aug-15 23:54:47 +0300 ** INFO [hsbox.version] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
2016-Aug-15 23:54:49 +0300 ** ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  68[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2016-Aug-16 00:43:54 +0300 ** DEBUG [hsbox.steamapi] - Getting fresh data from the API for 3 steamids
2016-Aug-16 00:52:50 +0300 ** DEBUG [hsbox.steamapi] - Getting fresh data from the API for 14 steamids



You think this might cause the issue ?`



You think this might cause the issue ?

**Comment by bugdone** [comment]
No. That happens when you already have Headshotbox started or when another application is using that port.
How many demos do you have? Maybe there's no one banned.

**Comment by iFEARR** [comment]
~100 demos
One match I played with this guy http://steamcommunity.com/profiles/76561198089644097
http://i.imgur.com/hni7Q2p.png

**Comment by bugdone** [comment]
Have you played with him in the last 396 days, or before?
To be honest, it should be a bug somewhere, it's improbable to have no cheaters in 100 demos.

**Comment by iFEARR** [comment]
I played with him a few days ago. So it checks if they got VAC after I played with them ?

**Comment by bugdone** [comment]
Yes.

**Comment by ajohnsen** [comment]
i dont think iFEARRs issue is the same one as i reported here. I updated the first comment a little to try and describe it better.

**Comment by bugdone** [comment]
Yes, you are right. I continued the discussion here for his bug because I was lazy.
@iFEARR If you still think there is a bug, file a new issue please.
