### ISSUE TITLE
Feature request: Ability to edit dates

### ISSUE THREAD

**Issue by Forvana** [bugdone/headshotbox#178]
I imported all of my Faceit demos and they all showed the upload dates instead of game dates, as expected. 

![headshotbox faceit dates](https://cloud.githubusercontent.com/assets/1572440/18249776/3528f2b0-7335-11e6-8894-7a8348c28047.png)

I looked into the sqlite file to change the time stamps manually, but they don't make sense.

**DO NOTE:** The given dates are ValveMM games because I couldn't find my Faceit demos in the sqlite file _AND_ I assumed that I need to input the same time stamp format when manually adding dates.

Example of two demos: 
`Timestamp: 1420692729`
`Date: Jan 7, 2015, 20:52`

`Timestamp: 1456004256`
`Date: Feb 20, 2016, 13:37`

Depending on the frequency of this problem, I believe adding a feature to edit dates could be nice :)

**Comment by bugdone** [comment]
Is your timezone UTC-8? I store UTC timestamps in the database, but display them in the local timezone.

If the file *demo.dem.json* exists for a demo named *demo.dem*, this file is parsed as json and the data is imported into HeadshotBox.

Example of such a json file:
```
{
    "metrics": {
        "elo": 1061
    },
    "timestamp": 1465930241
}
```
The *metrics/elo* number is displayed in the **Rank** column if present.

**Comment by Forvana** [comment]
Pardon me if I don't completely understand (running on 3 hours of sleep and sick) but does this mean if i created a json to go along with my Faceit demo--

faceitDemo.dem.json:
```
{
    "timestamp": XXXXXXXXXX
}
```

--Headshotbox should display the date with the time stamp i set it as, correct?

If so, how would I convert a date such as February 20, 2016 to a 10-digit time stamp?

**Comment by bugdone** [comment]
You would need to re-trigger the demo parsing so the json file is read.
As for the conversion, using your favorite programming language :) Find a library that parses a string to a date object and use a function that returns the UTC timestamp of the date.

**Comment by Forvana** [comment]
Got it, thanks for the help!
