### ISSUE TITLE
Wrong number of rounds found

### ISSUE THREAD

**Issue by Janzert** [bugdone/headshotbox#180]
My latest MM game was a 15:15 draw, but headshotbox shows it as a 15:14 win. It seems to be missing the result from the penultimate round of the first half. During the demo parsing headshotbox gave "Total number of rounds differs in demo..." for every round from the last round of the first half on. 

Log output of demo parse: [rounds off.txt](https://github.com/bugdone/headshotbox/files/478403/rounds.off.txt)

Demo file: [match730_003165576151976378500_0279806251_125.dem](http://janzert.com/match730_003165576151976378500_0279806251_125.dem)

[Edit: corrected round that seems to be missing.]

**Comment by bugdone** [comment]
Round 14 is missing some game events (round_start and player_spawn) and gets conflated with round 15.
While I could hack some code to make this weird case work, I don't think it's worth it.
Game events can randomly get lost when the demo is recorded and there's no proper fix for this issue.
