### ISSUE TITLE
Error getting status from steam api

### ISSUE THREAD

**Issue by ajohnsen** [bugdone/headshotbox#181]
I have started getting this exception in spammed in the logs the last few days/week.

`INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://api.steampowered.com: Connection reset
sep 19, 2016 3:40:44 PM org.apache.http.impl.client.DefaultHttpClient tryExecute
INFO: Retrying request to {}->http://api.steampowered.com`

So it doesn't get the vac status for the different players, seems unstable.
Sometime it updates them.

**Comment by bugdone** [comment]
There's nothing I can do here. Just some weird TCP connection problems between you computer and the Steam API.
