### ISSUE TITLE
No VAC bans since August

### ISSUE THREAD

**Issue by mschmitt** [bugdone/headshotbox#184]
So I took a break from CS:GO during most of August and September, and now that I'm back and have played about 30 matches, I notice that all VAC badges in headshotbox are from before my break.

I took the time to click through ALL people I played with after I returned and found no VAC ban on any of their steam profiles. There was however a fairly high percentage (maybe 10-20%) of private profiles among them where I couldn't see anything.

When I look at the "yearly" graph at vac-ban.com, I see that there is a steep drop in one of their curves (I think it's the inventory value) from x to zero around august. 

Has something changed in the Steam API about how 3rd party services can detect VAC banned profiles? Or have things taken a turn for the best and I've played without cheaters for the past 6 weeks?

**Comment by bugdone** [comment]
I don't think they changed something in the API. Even if they would have, the 10-20% private profiles couldn't account for almost 100% of the inventory value.

Also remember that VAC takes a long time (or never) to catch a cheater so it makes sense that the older the demo is, the more banned players (also they have more time to get banned in other games).
