### ISSUE TITLE
Average RWS not shown on some players

### ISSUE THREAD

**Issue by ajesina** [bugdone/headshotbox#185]
For some players in my player list, average RWS are not shown.
It is consistently not showing for the same players.

Tried
- restarting the app
- adding/removing demos

**Comment by bugdone** [comment]
are the demos recorded before 06.2015?

**Comment by ajesina** [comment]
Some of them might be, yes.

**Comment by bugdone** [comment]
HeadshotBox only parses damage info from demos recorded after 30.06.2015.
For these demos, both RWS and ADR won't show up. If ADR shows up but RWS doesn't then that should be a bug. If you manage to get such a demo, please send it to me.

**Comment by ajesina** [comment]
The issue isn't with any single demo, but with the overview of the average stats for the player.
It seems like if the list of demos for a player consists of some where RWS cannot be calculated and some where it can, it doesn't display an average in the stats overview.

**Comment by bugdone** [comment]
Find a player for which the bug triggers and post here the response of:
```
http://localhost:4000/api/player/<player_steamid64>/stats
```
eventually replacing the host and port with what you use.

**Comment by ajesina** [comment]
`{"tied":10,"kills":1116,"open_kills_attempted":299,"won":27,"hs":361,"assists":275,"weapons":[{"kills":1,"hs":0,"name":"mag7"},{"kills":11,"hs":6,"name":"mp9"},{"kills":7,"hs":0,"name":"inferno"},{"kills":25,"hs":12,"name":"fiveseven"},{"kills":145,"hs":46,"name":"m4a1"},{"kills":16,"hs":2,"name":"galil"},{"kills":27,"hs":12,"name":"ssg08"},{"kills":336,"hs":124,"name":"ak47"},{"kills":20,"hs":7,"name":"m4a4"},{"kills":37,"hs":13,"name":"tec9"},{"kills":13,"hs":0,"name":"hegrenade"},{"kills":36,"hs":7,"name":"famas"},{"kills":85,"hs":33,"name":"ump45"},{"kills":2,"hs":0,"name":"mp7"},{"kills":1,"hs":1,"name":"cz75a"},{"kills":28,"hs":16,"name":"glock"},{"kills":10,"hs":5,"name":"mac10"},{"kills":8,"hs":2,"name":"p90"},{"kills":68,"hs":30,"name":"usp"},{"kills":54,"hs":24,"name":"p250"},{"kills":2,"hs":1,"name":"deagle"},{"kills":180,"hs":20,"name":"awp"},{"kills":4,"hs":0,"name":"knife"}],"rounds_t":884,"lost":28,"1v1_attempted":36,"hs_percent":32.34767025089606,"deaths":1091,"1v1_won":20,"damage":114235,"rounds_with_damage_info":1490,"entry_kills":75,"open_kills":146,"rws":"NaN","rounds":1654,"rating":0.9908170597156292,"entry_kills_attempted":170,"rounds_with_kills":{"0":883,"1":496,"2":212,"3":58,"4":3,"5":2}}`

**Comment by bugdone** [comment]
Ooops `"rws":"NaN"`. Can you please send me the headshotbox.sqlite file?

**Comment by ajesina** [comment]
[headshotbox.zip](https://github.com/bugdone/headshotbox/files/635052/headshotbox.zip)
