### ISSUE TITLE
How to have clients download demos?

### ISSUE THREAD

**Issue by Rsslone** [bugdone/headshotbox#188]
I have openID realm set to my IP and steam ID as mine but my friend is trying to download a demo on another computer but doesnt see the button. Help.

**Comment by bugdone** [comment]
Have you enabled Demo Downloads in Settings?

**Comment by Rsslone** [comment]
Yeah I can see the download button on my end, but not on his.

**Comment by bugdone** [comment]
https://github.com/bugdone/headshotbox/releases/tag/0.16.3
