### ISSUE TITLE
Cannot parse demo

### ISSUE THREAD

**Issue by Magen97** [bugdone/headshotbox#192]
When running on a linux server, no demo can be parsed. This happens to everyone. 

![unbenannt](https://cloud.githubusercontent.com/assets/10731204/25072089/140c2286-22c7-11e7-98b9-2d41a20dbb4c.PNG)

**Comment by bugdone** [comment]
Try running the demoinfogo binary manually.
Eg. `~/hsbox/# ./demoinfogo match.dem -hsbox` if you have a demo file named match.dem

**Comment by Magen97** [comment]
Okay i solved it myself and it was my fault. 
I could not run the original script because it told me "demoinfogo no such file or directory". I was messing around earlier with a self-compiled version of demoinfogo and replaced it with that. These errors probabbly result of a complete different version of demoinfogo. I just found out that I need to install 32-Bit Binaries and now its working like a charm with the original 0.16.4 demoinfogo.

Guess this can be closed now.
