### ISSUE TITLE
Valve MM Demo errors out on parsing every launch

### ISSUE THREAD

**Issue by zergl64** [bugdone/headshotbox#194]
Match Download link: steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-STLCF-CEMkr-OjaEC-zLyRG-wcpmJ

Output: [log.txt](https://github.com/bugdone/headshotbox/files/949088/log.txt)

CSGO Demos Manager parses it perfectly fine as far as I can tell. Re-Downloaded it a couple times to rule out file corruption on my end.

**Comment by bugdone** [comment]
This was actually a limitation in my implementation.

The demo is missing the last kill event from the first round so the stats won't be accurate.
