### ISSUE TITLE
Refresh players Steam Data not working Bug?

### ISSUE THREAD

**Issue by Haxzer** [bugdone/headshotbox#201]
My steam data shows as last updated 90 days ago, and the button to refresh players Steam Data is not doing anything.

EDIT: I have restarted HeadshotBox and I have restarted my computer, this does not do any difference.

**Comment by bugdone** [comment]
Check the logs

**Comment by Chikkn** [comment]
Getting this error in the logs, hope it helps.: 

`17-08-26 12:39:09 desktop-chikken INFO [hsbox.handler:146] - Refresh players steam info
17-08-26 12:40:17 desktop-chikken ERROR [hsbox.handler:221] - 
                                                                     [37mjava.lang.Thread.run[m  [32m                                              [m
                                     [37morg.eclipse.jetty.util.thread.QueuedThreadPool$3.run[m  [32m                   QueuedThreadPool.java:  555[m
                                    [37morg.eclipse.jetty.util.thread.QueuedThreadPool.runJob[m  [32m                   QueuedThreadPool.java:  635[m
                                            [37morg.eclipse.jetty.io.AbstractConnection$2.run[m  [32m                 AbstractConnection.java:  540[m
                                       [37morg.eclipse.jetty.server.HttpConnection.onFillable[m  [32m                     HttpConnection.java:  257[m
                                              [37morg.eclipse.jetty.server.HttpChannel.handle[m  [32m                        HttpChannel.java:  310[m
                                                   [37morg.eclipse.jetty.server.Server.handle[m  [32m                             Server.java:  497[m
                                   [37morg.eclipse.jetty.server.handler.HandlerWrapper.handle[m  [32m                     HandlerWrapper.java:   97[m
[37mring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle[m  [32m                                              [m
                                                      [33mring.adapter.jetty/proxy-handler/[1;33mfn[m  [32m                               jetty.clj:   24[m
                                                  [33mring.middleware.session/wrap-session/[1;33mfn[m  [32m                             session.clj:  103[m
                                                      [33mring.middleware.flash/wrap-flash/[1;33mfn[m  [32m                               flash.clj:   35[m
                                [33mring.middleware.multipart-params/wrap-multipart-params/[1;33mfn[m  [32m                    multipart_params.clj:  133[m
                                                    [33mring.middleware.params/wrap-params/[1;33mfn[m  [32m                              params.clj:   64[m
                                      [33mring.middleware.nested-params/wrap-nested-params/[1;33mfn[m  [32m                       nested_params.clj:   86[m
                                    [33mring.middleware.keyword-params/wrap-keyword-params/[1;33mfn[m  [32m                      keyword_params.clj:   35[m
                                                      [33mhsbox.handler/wrap-cache-control/[1;33mfn[m  [32m                             handler.clj:  226[m
                                                          [33mhsbox.handler/wrap-exception/[1;33mfn[m  [32m                             handler.clj:  219[m
                                      [33mring.middleware.http-response/wrap-http-response/[1;33mfn[m  [32m                       http_response.clj:    8[m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                                core.clj:  156[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                                core.clj:  648[m
                                                                                      [37m...[m  [32m                                              [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  148[m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  151[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                                core.clj: 2592[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                                core.clj:  151[m
                                                             [33mcompojure.core/if-context/[1;33mfn[m  [32m                                core.clj:  220[m
                                                                         [33mhsbox.handler/[1;33mfn[m  [32m                             handler.clj:  203[m
                                                                                      [37m...[m  [32m                                              [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  148[m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  151[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                                core.clj: 2592[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                                core.clj:  151[m
                                                        [33mring.middleware.cors/wrap-cors/[1;33mfn[m  [32m                                cors.clj:  156[m
                                                   [33mring.middleware.json/wrap-json-body/[1;33mfn[m  [32m                                json.clj:   46[m
                                               [33mring.middleware.json/wrap-json-response/[1;33mfn[m  [32m                                json.clj:   87[m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                                core.clj:  156[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                                core.clj:  648[m
                                                                                      [37m...[m  [32m                                              [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  148[m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  151[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                                core.clj: 2592[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                                core.clj:  151[m
                                                             [33mcompojure.core/if-context/[1;33mfn[m  [32m                                core.clj:  220[m
                                                                         [33mhsbox.handler/[1;33mfn[m  [32m                             handler.clj:  130[m
                                                                                      [37m...[m  [32m                                              [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  148[m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  151[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                                core.clj: 2592[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                                core.clj:  151[m
                                                                                      [37m...[m  [32m                                              [m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                                core.clj:  156[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                                core.clj:  648[m
                                                                                      [37m...[m  [32m                                              [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  148[m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                                core.clj:  151[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                                core.clj: 2592[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                                core.clj:  151[m
                                                              [33mcompojure.core/if-method/[1;33mfn[m  [32m                                core.clj:   27[m
                                                               [33mcompojure.core/if-route/[1;33mfn[m  [32m                                core.clj:   45[m
                                                        [33mcompojure.core/wrap-route-info/[1;33mfn[m  [32m                                core.clj:  126[m
                                                  [33mcompojure.core/wrap-route-middleware/[1;33mfn[m  [32m                                core.clj:  122[m
                                                             [33mcompojure.core/make-route/[1;33mfn[m  [32m                                core.clj:  135[m
                                                                      [33mhsbox.handler/fn/[1;33mfn[m  [32m                             handler.clj:  143[m
                                                                                      [37m...[m  [32m                                              [m
                                                         [33mhsbox.steamapi/[1;33mget-steamids-info[m  [32m                            steamapi.clj:   47[m
                                                         [33mhsbox.steamapi/[1;33mget-steamids-info[m  [32m                            steamapi.clj:   55[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                                core.clj:  641[m
                                                                         [33mclojure.core/[1;33mseq[m  [32m                                core.clj:  137[m
                                                                                      [37m...[m  [32m                                              [m
                                                                      [33mclojure.core/map/[1;33mfn[m  [32m                                core.clj: 2646[m
                                                [33mhsbox.steamapi/[1;33mget-steamids-info-from-api[m  [32m                            steamapi.clj:   21[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                                core.clj:  646[m
                                                                                      [37m...[m  [32m                                              [m
                                                                  [33mwatt.core/method->fn/[1;33mfn[m  [32m                                core.clj:   44[m
                                                     [33mclj-http.client/wrap-unknown-host/[1;33mfn[m  [32m                              client.clj:  807[m
                                                             [33mclj-http.links/wrap-links/[1;33mfn[m  [32m                               links.clj:   51[m
                                                         [33mclj-http.cookies/wrap-cookies/[1;33mfn[m  [32m                             cookies.clj:  124[m
                                                           [33mclj-http.client/wrap-method/[1;33mfn[m  [32m                              client.clj:  701[m
                                                    [33mclj-http.client/wrap-nested-params/[1;33mfn[m  [32m                              client.clj:  787[m
                                                      [33mclj-http.client/wrap-form-params/[1;33mfn[m  [32m                              client.clj:  757[m
                                                     [33mclj-http.client/wrap-content-type/[1;33mfn[m  [32m                              client.clj:  586[m
                                                  [33mclj-http.client/wrap-accept-encoding/[1;33mfn[m  [32m                              client.clj:  610[m
                                                           [33mclj-http.client/wrap-accept/[1;33mfn[m  [32m                              client.clj:  596[m
                                                       [33mclj-http.client/wrap-exceptions/[1;33mfn[m  [32m                              client.clj:  219[m
                                                  [33mclj-http.client/wrap-output-coercion/[1;33mfn[m  [32m                              client.clj:  469[m
                                        [33mclj-http.client/wrap-additional-header-parsing/[1;33mfn[m  [32m                              client.clj:  553[m
                                                   [33mclj-http.client/wrap-input-coercion/[1;33mfn[m  [32m                              client.clj:  519[m
                                                    [33mclj-http.client/wrap-decompression/[1;33mfn[m  [32m                              client.clj:  339[m
                                                        [33mclj-http.client/wrap-redirects/[1;33mfn[m  [32m                              client.clj:  267[m
                                                              [33mclj-http.client/wrap-url/[1;33mfn[m  [32m                              client.clj:  798[m
                                                        [33mclj-http.client/wrap-user-info/[1;33mfn[m  [32m                              client.clj:  694[m
                                                            [33mclj-http.client/wrap-oauth/[1;33mfn[m  [32m                              client.clj:  681[m
                                                       [33mclj-http.client/wrap-basic-auth/[1;33mfn[m  [32m                              client.clj:  671[m
                                                     [33mclj-http.client/wrap-query-params/[1;33mfn[m  [32m                              client.clj:  646[m
                                                      [33mclj-http.headers/wrap-header-map/[1;33mfn[m  [32m                             headers.clj:  143[m
                                                   [33mclj-http.client/wrap-request-timing/[1;33mfn[m  [32m                              client.clj:  832[m
                                                                                      [37m...[m  [32m                                              [m
                                                                    [33mclj-http.core/[1;33mrequest[m  [32m                                core.clj:  316[m
                                  [37morg.apache.http.impl.client.CloseableHttpClient.execute[m  [32m                CloseableHttpClient.java:   82[m
                                 [37morg.apache.http.impl.client.InternalHttpClient.doExecute[m  [32m                 InternalHttpClient.java:  184[m
                                      [37morg.apache.http.impl.execchain.RedirectExec.execute[m  [32m                       RedirectExec.java:  110[m
                                         [37morg.apache.http.impl.execchain.RetryExec.execute[m  [32m                          RetryExec.java:   88[m
                                      [37morg.apache.http.impl.execchain.ProtocolExec.execute[m  [32m                       ProtocolExec.java:  184[m
                                    [37morg.apache.http.impl.execchain.MainClientExec.execute[m  [32m                     MainClientExec.java:  236[m
                             [37morg.apache.http.impl.execchain.MainClientExec.establishRoute[m  [32m                     MainClientExec.java:  380[m
                       [37morg.apache.http.impl.conn.BasicHttpClientConnectionManager.connect[m  [32m   BasicHttpClientConnectionManager.java:  338[m
                    [37morg.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect[m  [32mDefaultHttpClientConnectionOperator.java:  141[m
                   [37morg.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket[m  [32m       PlainConnectionSocketFactory.java:   74[m
                                                                  [37mjava.net.Socket.connect[m  [32m                                              [m
                                                         [37mjava.net.SocksSocketImpl.connect[m  [32m                                              [m
                                                         [37mjava.net.PlainSocketImpl.connect[m  [32m                                              [m
                                                 [37mjava.net.AbstractPlainSocketImpl.connect[m  [32m                                              [m
                                        [37mjava.net.AbstractPlainSocketImpl.connectToAddress[m  [32m                                              [m
                                               [37mjava.net.AbstractPlainSocketImpl.doConnect[m  [32m                                              [m
                                          [37mjava.net.DualStackPlainSocketImpl.socketConnect[m  [32m                                              [m
                                               [37mjava.net.DualStackPlainSocketImpl.connect0[m  [32m                                              [m
[1;31mjava.net.SocketException[m: [3mPermission denied: connect[m`

**Comment by bugdone** [comment]
Looks like your firewall blocks HeadshotBox. Are there other 
`Permission denied: connect`
lines in the log?
I suspect there must be another one when you start HeadshotBox and it tries to check for updates.

**Comment by Chikkn** [comment]
Yeah you are right, it happens when I start headshotbox through the .bat but not when I execute the .jar directly. 
Weird, but thanks, works for me again.

**Comment by bugdone** [comment]
Did you change the --port option in the .bat file?

**Comment by Chikkn** [comment]
Nope, checked that, nothing changed there: 

`start javaw -jar hsbox-0.17.0-standalone.jar --port 4000 --systray`

**Comment by bugdone** [comment]
Maybe javaw.exe is firewalled but whatever process is associated with .jar files is not.
