### ISSUE TITLE
How to install realm?

### ISSUE THREAD

**Issue by Bl4CkGuuN** [bugdone/headshotbox#202]
I've got a domain, but don't know how to use it with headshotbox and realm ...

Also did I need the dem.info?

Greetz

**Comment by bugdone** [comment]
Have you read the [OpenID setup](https://github.com/bugdone/headshotbox/wiki/Setup#steam-openid)?

No, you don't need dem.info files. They are only useful for extracting the demo's timestamp.

**Comment by Bl4CkGuuN** [comment]
Yeah, but I dont know how to set up a realm and also I dont know how to host headshotbox on my domain, becaue I've got multiple websites on my server...

**Comment by bugdone** [comment]
You just have to tell Headshotbox the URL where it will be accessible from the outside.

**Comment by Bl4CkGuuN** [comment]
Hm, thats in the .sh: 

> java -jar hsbox-0.17.0-standalone.jar --admin-steamid 76*************32 --openid-realm http://headshotbox.domain.de

But it is still starting on port 4000 and the realm validation is disabled.



> INFO [hsbox.core:67] - HeadshotBox 0.17.0
> INFO [hsbox.version:21] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-linux-version
> Jul 28, 2017 5:52:15 PM org.openid4java.server.RealmVerifier setEnforceRpId
> WARNING: RP discovery / realm validation disabled;
> Jul 28, 2017 5:52:15 PM org.openid4java.consumer.ConsumerManager setMaxAssocAttempts
> INFO: Associations disabled.
> 2017-07-28 17:52:15.101:INFO:oejs.Server:main: jetty-9.2.z-SNAPSHOT
> 2017-07-28 17:52:15.127:INFO:oejs.ServerConnector:main: Started ServerConnector@746c2814{HTTP/1.1}{0.0.0.0:4000}
> 2017-07-28 17:52:15.160:INFO:oejs.Server:main: Started @4643ms
> DEBUG [hsbox.version:23] - Latest version 0.17.0
> DEBUG [hsbox.indexer:138] - Indexer started

**Comment by Bl4CkGuuN** [comment]
It is working for now... but only if I start hsbox with a port like this: 

> java -jar hsbox-0.17.0-standalone.jar --port 4000 --admin-steamid 76************32 --openid-realm http://hsbox.domain:4000/

**Comment by Bl4CkGuuN** [comment]
Im fine with this...

can I set multiple admins?

**Comment by bugdone** [comment]
No, you cannot set multiple admins.

**Comment by Bl4CkGuuN** [comment]
Ok, thanks.
