### ISSUE TITLE
"Rating (?)" link on player page is dead

### ISSUE THREAD

**Issue by mschmitt** [bugdone/headshotbox#203]
It seems HLTV have a new rating system: https://www.hltv.org/news/20695/introducing-rating-20

**Comment by bugdone** [comment]
I guess I'll have to copy the content from the old page into HeadshotBox 
https://web.archive.org/web/20170127061156/https://www.hltv.org/?pageid=242

hltv rating 2.0 has a secret formula so I cannot implement that
