### ISSUE TITLE
Some demos aren't showing up

### ISSUE THREAD

**Issue by StoneColeQ** [bugdone/headshotbox#206]
Some demos, only few esea matches it seems, don't show up. It tries to analyze the demo I presume, as it shows up in the counter, but I don't get the ability to watch it.

**Comment by bugdone** [comment]
What counter?
Do the matches show up in the match list?
Take a look at the logs and show me the parsing error.

**Comment by StoneColeQ** [comment]
The counter that says how many demos left to analyze in the top right. All my demos show up there, counting down from 46 demos. But for the demo count in "Player List", it's 43. I also can't find those 3 demos to watch.

I don't get a parsing error, everything just proceeds as normal, except they just down show up. I've tried only analyzing those yet they still don't show up. Where are the logs stored?

I've uploaded a few demos, all ESEA leauge matches: https://drive.google.com/open?id=1w0lyW74MVfqrMPyw2uk0t7T2hSPDavrF

The problematic ones are:
esea_match_11587198
esea_match_11362552
esea_match_11364311

Also, are you planning to support popflash?

Thanks.

**Comment by bugdone** [comment]
https://github.com/bugdone/headshotbox/wiki/Setup#files

**Comment by StoneColeQ** [comment]
Here is the log.

[headshotbox.log](https://github.com/bugdone/headshotbox/files/1523122/headshotbox.log)

**Comment by bugdone** [comment]
The demos are corrupted (Like #148)
There's nothing to fix here. Probably even csgo can't play them from start to end.

**Comment by StoneColeQ** [comment]
The issues seems to have fixed itself. Idk why. I'm just letting you know.

**Comment by bugdone** [comment]
Thanks. That makes no sense.
If the code and the dem files didn't change, then the code is non-deterministic? Seems improbable.
