### ISSUE TITLE
Failing to process demo

### ISSUE THREAD

**Issue by ajohnsen** [bugdone/headshotbox#210]
Getting this stacktrace when trying to parse this demo:
steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-NMH6k-tGcOU-tHf4J-mxys5-dLaxJ

`18-07-25 20:42:13 Tower DEBUG [hsbox.indexer:76] - Adding path /demoes/replays/match730_003290698404111319097_1247390871_188.dem
18-07-25 20:42:13 Tower INFO [hsbox.demo:317] - Processing /demoes/replays/match730_003290698404111319097_1247390871_188.dem
18-07-25 20:42:14 Tower ERROR [hsbox.indexer:87] - Cannot parse demo /demoes/replays/match730_003290698404111319097_1247390871_188.dem
18-07-25 20:42:14 Tower ERROR [hsbox.indexer:88] -
               hsbox.core.main
                           ...
              hsbox.core/-main     core.clj:  46
              hsbox.core/-main     core.clj:  84
             hsbox.indexer/run  indexer.clj: 148
        hsbox.indexer/add-demo  indexer.clj:  78
      hsbox.demo/get-demo-info     demo.clj: 319
         hsbox.demo/parse-demo     demo.clj:  60
hsbox.demo/parse-demo/do-parse     demo.clj:  57
java.lang.AssertionError: Assert failed:
                          (zero? (:exit proc))`

**Comment by ajohnsen** [comment]
I think that this also breaks the updating of banned status from steam
Because when i press the "Refresh players steam data" button, i just get the stacktrace again in the log file. and it wont update the status.

**Comment by bugdone** [comment]
The link expired. Do you still have the demo?

**Comment by ajohnsen** [comment]
Yeah, i uploaded the demo here: https://s3.eu-central-1.amazonaws.com/headshotbox-failing-demo/replays.zip

**Comment by bugdone** [comment]
Is that the only replay it cannot parse?
I cannot reproduce it.

**Comment by ajohnsen** [comment]
Yeah, thats the only demo im having problems with :/ 
I tried to redownload it as well, but no change.

**Comment by bugdone** [comment]
No. The code failed because the binary demoinfogo didn't exit with status code 0.
So every time you fire up Headshotbox it tries to parse it and fails?

**Comment by ajohnsen** [comment]
yeah, i get the error every time it tries to parse it.

**Comment by bugdone** [comment]
After this parsing fails, do other demos get parsed successfully?

**Comment by ajohnsen** [comment]
Yeah, all other demos get parsed just fine.

**Comment by bugdone** [comment]
I assume you run it on linux.
Run demoinfogo manually on that demo.
`./demoinfogo -hsbox demo.dem`
And see if there's any output to stder/stdout. Also grab the exit status code (run `echo $?` after running demoinfogo).
Get a core dump if you can (`ulimit -c unlimited` before running demoinfogo).

**Comment by ajohnsen** [comment]
I tried to run it manually now, and i ended up with an segmentation fault.
Here is the core dump: https://s3.eu-central-1.amazonaws.com/headshotbox-failing-demo/core

**Comment by bugdone** [comment]
I cannot get anything useful out of the core you provided:

> BFD: Warning: /demoinfogo/core is truncated: expected core file size >= 131178496, found: 819200.
> Cannot access memory at address 0x2aa4b908
> Cannot access memory at address 0x2aa4b904

Did you run it with `-hsbox`? I did manage to get a crash running it without `-hsbox` but it doesn't crash with `-hsbox`.

I fixed the crash I found, but Headshotbox runs demoinfogo always with `-hsbox` so I don't think it fixes your issue.

**Comment by ajohnsen** [comment]
Yeah, i ran it with this command: ` ./demoinfogo -hsbox /demoes/replays/match730_003290698404111319097_1247390871_188.dem`

I've been running it in a docker container, but one works and my main one didn't.
So i tried to fire up a temp one to run the demoinfogo, and i got a seg fault. Its probably an issue on my side / docker.

Are you able to recreate it by starting the docker and running it? 
This is how i did it:
`docker run -it --rm -v /mnt/user/data/csgo-demoes/:/demoes ajohnsen/headshotbox  bash`
Then running:
`./demoinfogo -hsbox /demoes/match730_003290698404111319097_1247390871_188.dem
`

**Comment by bugdone** [comment]
I can only crash it if I create a `i386/ubuntu:12.04` docker image, copy the binary there and run
`./demoinfogo match730_003290698404111319097_1247390871_188.dem`.
If I add `-hsbox` the demo parses fine.

**Comment by ajohnsen** [comment]
This is really weird:
I tried it with `i386/ubuntu` and `i386/openjdk` which `ajohnsen/headshotbox` is built on, and it works on both of them, but not on `ajohnsen/headshotbox` :s

I just force updated to the newest  `i386/openjdk` and recreated the docker image, and it seems like its working now. Thanks for helping me out with the problem, wonder why it suddenly couldn't process one of the demos.
