### ISSUE TITLE
Search for demos within subfolders

### ISSUE THREAD

**Issue by 201808071800** [bugdone/headshotbox#214]
I have my demos sorted in a general CSGO folder as such:
CSGO
----Headshot Box (folder containing Headshot Box files)
----Demos
--------Competitive
------------YYYY-MM-DD (folder with all demos from some date)
--------Wingman
------------YYYY-MM-DD (folder with all demos from some date)

Is it possible for your program to recursively search through the directory that I have saved in its settings for all valid demo files? I have code written that may be reusable from a program that I wrote. I'm more than happy to share it if it will expedite having this feature added to Headshot Box.

Thanks.

**Comment by bugdone** [comment]
It does recursively search for demos.

**Comment by 201808071800** [comment]
Here is what I did wrong. I get my Steam demos from [the instructions here](https://www.reddit.com/r/GlobalOffensive/comments/8lyzb6/so_the_steam_client_has_been_keeping_track_of/) to save as to my own folder structure rather than CS:GO itself. They come as bz2 files which need to be unzipped. This was honestly my mistake as I've never worked with demos and assumed that CS:GO, etc. could handle them as-is.

Also, my Wingman demos don't work in Headshot Box. Is there any chance that will be added as a feature, or should I just point the program to my competitive demos only?

**Comment by bugdone** [comment]
I don't think I'll bother with Wingman. The code makes lots of assumptions (5 players, 30 rounds, etc)

**Comment by 201808071800** [comment]
Fair enough. Thank you for the information! This looks to be a great offline complement to the couple stat websites out there.
