### ISSUE TITLE
Feature request: Support for Wingman

### ISSUE THREAD

**Issue by radriaanse** [bugdone/headshotbox#215]
With the new European GDPR, Valve needed to publish a lot more data about your account.
This also meant making all your demo's available for download, which include those of Wingman.

You can find these over at: https://steamcommunity.com/profiles/--steamid--/gcpd/730/?tab=matchhistorywingman

I've tried to just import a downloaded one, but it fails with:
```
18-09-15 09:58:29 stats ERROR [hsbox.indexer:87] - Cannot parse demo /home/games/csgo/headshotbox/replays/003293343401738502334_1035726588.dem
18-09-15 09:58:29 stats ERROR [hsbox.indexer:88] - 
         hsbox.core.main                    
                     ...                      
        hsbox.core/-main     core.clj:  46  
        hsbox.core/-main     core.clj:  84  
       hsbox.indexer/run  indexer.clj: 148 
  hsbox.indexer/add-demo  indexer.clj:  78  
hsbox.demo/get-demo-info     demo.clj: 351 
  hsbox.demo/enrich-demo     demo.clj: 312 
java.lang.AssertionError: Assert failed: Demo /home/games/csgo/headshotbox/replays/003293343401738502334_1035726588.dem has 0 rounds and 0 players
                          (not (or (empty? (:rounds enriched)) (empty? (:players enriched))))
```

So I suppose because of the different demo format there will need to be some changes to the parsing?

**Comment by bugdone** [comment]
I am not interested in implementing this.
The demo format is not different, but yes, more parsing code needs to be written.
It looks like the wingman demos are also deleted after 2 weeks.
