### ISSUE TITLE
Fetching Data From Steam API / Refresh Steam data not working

### ISSUE THREAD

**Issue by MSVilsen** [bugdone/headshotbox#219]
I've continuously been trying to refresh the Steam data so I can see banned players again. It doesn't work, though and by now it's a 103 days since the last update. What can I do to fix this? I'm not sure how to paste my log here either as I'm not too savvy with this kind of thing.

**Comment by clugg** [comment]
Are you on the latest version (0.17.4)? Have you tried restarting a few times? If not, both of these might help. You can get the log from `%USERPROFILE%\.config\headshotbox` (press Windows+R to open Run dialog, enter the previous text) - it's a file called `headshotbox.log`. It will be rather large if you've been running the software for a while, so maybe delete the log file first, run the program and attempt to reproduce your issue, then upload it, as it will be fresh and should only contain relevant information.

**Comment by bugdone** [comment]
closing due to lack of feedback
