### ISSUE TITLE
Knife round being counted

### ISSUE THREAD

**Issue by spacecow123** [bugdone/headshotbox#229]
Can you tell me what hsbox is looking for to tell the difference between a knife round and a regular round? I am using pugsetup (https://github.com/splewis/csgo-pug-setup) for my matches. A while a go hsbox did exclude knife rounds from the stats but I don't know what I changed that made it so knife rounds are now being counted.

Thanks!

**Comment by bugdone** [comment]
Kinda lazy to try to understand the code :), but it I think it ignores rounds with timelimit longer that 115 seconds (since both esea and faceit have more, this heuristic worked fine).

**Comment by spacecow123** [comment]
Thank you, that fixed the issue!
