### ISSUE TITLE
No connection to http://127.0.0.1:4000/

### ISSUE THREAD

**Issue by jcoester** [bugdone/headshotbox#23]
sometimes it works sometimes theres no connection to the website which is really annoying :(

maybe you could host the site on a server if thats the problem? 
if so i would donate if you want =)

PS: great work so far.

**Comment by lukealford** [comment]
Can please paste your log so we get a bit more info on why it's doing this.

"C://Users/<user>/.config/headshotbox/log.txt"

Answering your other question, the logistics behind having it as a on-line service is a little intense at the moment, eg bandwidth required to store demo's would be immense, then even getting the demo's from your steam account on-line would require connection to steam at the moment I'm not even if it's possible with the current Steam API.

**Comment by jcoester** [comment]
Thanks for your answer,

the problem is/was that you have to run the headshotbox.bat in the background while open the IP which i didn't knew. 
Maybe a litte hint can solve this "issue" :)

**Comment by lukealford** [comment]
Ah yes, this would confuse some users, Glad you figured it out yourself though! 

I'm sure as the project grows the documentation will with it, it's still very very young.

**Comment by abenea** [comment]
I have added a hint to the website in the Installing section.
