### ISSUE TITLE
Watch Replay Demo From Remote

### ISSUE THREAD

**Issue by mog3n** [bugdone/headshotbox#230]
I have my server setup remotely.

I would like others to watch demos without having to manually download all the files to their csgo/replays folder.

Is this possible? I.e. load a demo file from a remote server?

**Comment by bugdone** [comment]
Not as far as I know.

**Comment by mog3n** [comment]
> Not as far as I know.

Thank you! I love your app by the way. I've been using it to host a 30-person tournament for my friends. The level of detail is pretty incredible. Do you know if there's a way to recursively check sub folders for demo files? Much appreciated!

**Comment by bugdone** [comment]
It should find demos in all subdirectories of the configured directory. There's also a "Folder" filter in the player profile page.
