### ISSUE TITLE
New updates?

### ISSUE THREAD

**Issue by danvilar** [bugdone/headshotbox#232]
Hi, not really an issue, but is the project still active?

**Comment by bugdone** [comment]
Hi,
It's pretty dead. I started playing less and less csgo and lost interest.

**Comment by danvilar** [comment]
I see, it's a shame because it's the only viable tool in Linux for now. I wanted to try and pick it up where you left but I never worked with closure before. Who knows, maybe someday I'll do it. Thanks for your work though, I'm still using it everyday!

**Comment by danielstoeck** [comment]
We can't let this project die!

The stats overview is soooooo good.

**Comment by Rsslone** [comment]
I know this is old, but just for information for those checking.

Everything is working as intended at the date of posting. Even the short matches.

**Comment by bugdone** [comment]
Not everything :) So far I figured that:
- collateral and jump search keywords were broken
- stats for pistol rounds are wrong, they just filter for rounds 1 and 16

**Comment by Rsslone** [comment]
Just wondering, I got back into CS2, is this still being worked on? Demos are not being parsed it seems.
