### ISSUE TITLE
[Request] Add a license 

### ISSUE THREAD

**Issue by Max7cd** [bugdone/headshotbox#233]
Hey bugdone, 

I considered working on this project, but noticed, that it is missing a license.
I strongly believe that you have no problem with people deriving your work, but you can never be sure if there is no license.
I would be very happy to see a license, so I can start developing with the peace of mind, that my efforts go to help the community.

**Comment by bugdone** [comment]
Added MIT license.

**Comment by Max7cd** [comment]
Thanks a lot 👍
