### ISSUE TITLE
New parser fails to parse some demos

### ISSUE THREAD

**Issue by bugdone** [bugdone/headshotbox#241]
java.lang.AssertionError: Assert failed: Error: failed to fill whole buffer
java.lang.AssertionError: Assert failed: Error: Invalid UTF-8 sequence
java.lang.AssertionError: Assert failed: Error: Tried to remove an entity which doesn't exist
java.lang.AssertionError: Assert failed: Error: Unexpected end of file

**Comment by abenea** [comment]
Old parser fails to parse 29/31 of these demos.
