### ISSUE TITLE
[Linux] Parsing error demoinfogo (with temp fix)

### ISSUE THREAD

**Issue by sc0repi0** [bugdone/headshotbox#25]
Hey, first: I LOVE your work, thank you so much.

The problem: 
When I tried to set up HeadshotBox it wouldn't parse the demo folder, when the demos are not in the folder where demoinfogo is located:

>2015-Mai-10 13:03:03 +0200 dex-os ERROR [hsbox.indexer] - Cannot parse demo /home/dex/.local/share/Steam/steamapps/common/Counter-Strike Global Offensive/csgo/replays/match730_003068079370007478483_1242606074_135.dem #

>IOException java.io.IOException: Cannot run program "/home/dex/demoinfogo": error=2, Datei oder Verzeichnis nicht gefunden

(I had to get rid of the < > in the last line; after error=2 it states: file or folder not found)

The temporary solution (at least for me): 
- copy the whole content of the zip file to the folder where the demos are in 
- open headshotbox.sh and change the command to "java -jar /path/where/you/put/the/zipfile/contents/hsbox-version.number.standalone.jar 4000"
- let it parse

This temp fix is perfectly fine, if you ask me. No rush to fix it.

**Comment by bugdone** [comment]
Did you start HeadshotBox with headshotbox.sh? If yes, did you modify it before running it?

**Comment by yoyosan** [comment]
You'll need this:
```
sudo dpkg --add-architecture i386
sudo apt-get install -y libc6-i386
```

**Comment by sc0repi0** [comment]
Bugdone, actually yes, I had to. Don't know why I didn't mention that, sorry. Before that it wouldn't recognize the path the jar was in (same as headshotbox.sh), so I just set it to where the jar was.

I will test again and see if the problem persists.

**Comment by bugdone** [comment]
I assume it didn't work because you tried to run headshotbox.sh from another directory.
If you want that, I assume an easy fix would be to add `cd /path/to/headshotbox_dir` at the start of the .sh

**Comment by sc0repi0** [comment]
Hey, sorry for taking so long, illness and working is a terrible mix. I saw you made it a bug, so I guess I can say there was problem after all (and I'm not just an idiot in using it). I just tried it again:

* copied contents of zip into /home/user/dir/headshotbox
* tried to run it from there, out came this:
> Error: Unable to access jarfile hsbox-0.6.1-standalone.jar

* I then just ran the jar-file itself, it tried to parse and errored out like this:
>                  hsbox.core/-main             core.clj:   36
                hsbox.indexer/run          indexer.clj:   95
           hsbox.indexer/add-demo          indexer.clj:   54
         hsbox.demo/get-demo-info             demo.clj:   85
            hsbox.demo/parse-demo             demo.clj:   36
                              ...                           
            clojure.java.shell/sh            shell.clj:  116
           java.lang.Runtime.exec         Runtime.java:  620
   java.lang.ProcessBuilder.start  ProcessBuilder.java: 1029
      java.lang.ProcessImpl.start     ProcessImpl.java:  134
     java.lang.UNIXProcess.<init>     UNIXProcess.java:  248
java.lang.UNIXProcess.forkAndExec     UNIXProcess.java      
java.io.IOException: error=2, Datei oder Verzeichnis nicht gefunden
java.io.IOException: Cannot run program "/home/user/demoinfogo": error=2, Datei oder Verzeichnis nicht gefunden

* I then copied the whole content of the zip file to /home/user
* The whole thing works then

Since I'm not a programmer my best guess is, that the core of the problem is this:
> java.io.IOException: Cannot run program "/home/user/demoinfogo": error=2

This error will come even if the contents of the zip are in another directory. Headshotbox runs beautifully in the /home/user directory, but not in other directories.

I hope I could help :-/

**Comment by bugdone** [comment]
> With contents of zip into /home/user/dir/headshotbox:
> * tried to run it from there, out came this:
>
>> Error: Unable to access jarfile hsbox-0.6.1-standalone.jar

Just to clarify, did you:
`cd /home/user/dir/headshotbox && ./headshotbox.sh` ?

**Comment by sc0repi0** [comment]
Nope. I just used sh from /home, like in my bash scripts. With 
>cd /home/user/dir/headshotbox && ./headshotbox.sh
 
it works in the directory. Yippie! Thanks!

Note to self: Reproduction steps are more complex than you think.
