### ISSUE TITLE
doesnt work :)

### ISSUE THREAD

**Issue by chike1337** [bugdone/headshotbox#27]
Once i open the .bat the cmd runs for a bit, then demo demoinfogo.exe has stopped working ( copied it further down). The cmd keeps running but when i go to http://127.0.0.1:4000/ i get up the headshotbox, but no info. I have entered the demo directory and the steam API pls help

[Window Title]
demoinfogo.exe

[Main Instruction]
demoinfogo.exe has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

[Close program]

**Comment by bugdone** [comment]
You're not supposed to run demoinfogo.exe
Does this help?: https://github.com/bugdone/headshotbox/issues/14#issuecomment-100469163
Attach the log if not.

**Comment by beig** [comment]
doesn't work for me either on win8 64bit.

can't even get the help output from the demoinfogo.exe .. it crashes with 0xc0000007b
not a headshotbox issue.

i installed the vcs redistri package.

**Comment by beig** [comment]
downloaded the CSGO SKD and copied the demoinfogo.exe (which works - i can parse demos in the command line)

but i still get 

2015-Mai-26 02:06:25 +0200 Thyr ERROR [hsbox.indexer] - Cannot parse demo C:\Ste
am\SteamApps\common\Counter-Strike Global Offensive\csgo\replays\match730_003076
218811922251878_1732349714_191.dem
2015-Mai-26 02:06:25 +0200 Thyr ERROR [hsbox.indexer] -
         ←[37mhsbox.core.main←[m  ←[32m               ←[m
                     ←[37m...←[m  ←[32m               ←[m
        ←[33mhsbox.core/←[1;33m-main←[m  ←[32m   core.clj: 36←[m
       ←[33mhsbox.indexer/←[1;33mrun←[m  ←[32mindexer.clj: 95←[m
  ←[33mhsbox.indexer/←[1;33madd-demo←[m  ←[32mindexer.clj: 54←[m
←[33mhsbox.demo/←[1;33mget-demo-info←[m  ←[32m   demo.clj: 85←[m
   ←[33mhsbox.demo/←[1;33mparse-demo←[m  ←[32m   demo.clj: 37←[m
←[1;31mjava.lang.AssertionError←[m: ←[3mAssert failed: (zero? (:exit proc))←[m

**Comment by bugdone** [comment]
You can't use demoinfogo from SDK, Headshot Box comes with a modified one.
Try running demoinfogo in compatibility with Windows 7 or Windows XP SP3 and see if it still crashes.

**Comment by beig** [comment]
Oh okay. It does work on my work laptop (win8 64bit)

and linux is also working after the update. thank you.

**Comment by bugdone** [comment]
So you have 2 win8 64bit machines and it only works on one?
Have you tried changing the compatibility setting on the machine that doesn't work?

**Comment by beig** [comment]
I tried everything on the PC where it does not work. 
Re-installed the VCS Redistri (x64 and 86) ... maybe it's just my PC.
Don't know what else could be missing as the demoinfo is instantly crashing (not even showing the help output)

**Comment by bugdone** [comment]
So you tried running demoinfogo.exe with different compatibility options?

**Comment by beig** [comment]
I solved it.

I replaced my C:\Windows\SysWOW64\msvcp110.ddl with one downloaded from here http://www.dll-files.com/dllindex/dll-files.shtml?msvcp110
