### ISSUE TITLE
No tick_end for round 2 in demo nil

### ISSUE THREAD

**Issue by cxsquared** [bugdone/headshotbox#33]
I'm getting the repeating DEBUG log that says No tick_end for round 2 in demo nil and this is cause HeadshotBox to only show the first round data. Is it a problem with a corrupt demo download? I use Packrat to download my demos.

**Comment by bugdone** [comment]
What version are you using?
Non-MM demos are not supported yet.

**Comment by cxsquared** [comment]
I'm on version 0.5 and it was a MM demo.

**Comment by bugdone** [comment]
How many demos do you have for that player?

**Comment by cxsquared** [comment]
I believe the demo that doesn't work makes it 11.

**Comment by bugdone** [comment]
If you can pinpoint the demo that doesn't work, please send it to me.

**Comment by cxsquared** [comment]
Here's the demo and I tried to watch it in CSGO and it works just fine. I can navigate to all the rounds just fine. https://www.dropbox.com/s/etwwnymz7ts75v8/BrokenDemo_HeadshotBox.zip?dl=0

**Comment by bugdone** [comment]
I loaded up your demo in Headshot Box and seems fine. The "No tick_end" message doesn't show up, all kills are accounted for in stats, the demo shows up in demo list, I can find the 1v1 and 1v2 rounds in round search.
Can you please send me the headshotbox.sqlite file?

By the way, you mention:
> and this is cause HeadshotBox to only show the first round data

What do you mean by that? Where is data displayed only for the first round?

**Comment by cxsquared** [comment]
Here's what I mean by only showing one round in Headshot Box...
http://imgur.com/gJX4MYA

Also where would my headshotbox.sqlite file be located. I can't seem to find it anywhere.

**Comment by bugdone** [comment]
The .log and .sqlite files should be in c:/Users/<user>/.config/headshotbox/

**Comment by bugdone** [comment]
I think I figured it out: Headshot Box parsed the demo when wasn't complete (still downloading).
If you move the file out of the directory and back in when Headshot Box is running, it should parse it correctly.

**Comment by cxsquared** [comment]
Yep that seemed to fix the problem. Thank you!
