### ISSUE TITLE
Steam Profile link 

### ISSUE THREAD

**Issue by cherokee93** [bugdone/headshotbox#36]
Hello, thanks for this tool. It's Awesome!
Not sure where to post this, cause it's a suggestion.

Is it possible to have a button or something on a person profile to go straight to his steam profile?
It shouldn't be hard to do.

Thanks again :)

**Comment by bugdone** [comment]
For sure. Is it too unintuitive if the profile picture is the actual link to the steam profile?
Currently the avatars in a match page are links to steam profiles. Should I add a steam icon near a player's name for this?

**Comment by cherokee93** [comment]
Oh, Just noticed! But this is not working in the /player/123123123 page, that's why I didn't notice. Thanks for your work!

**Comment by cherokee93** [comment]
Well Explained.
![image](https://cloud.githubusercontent.com/assets/12370126/7686659/afb775fc-fd97-11e4-9366-d44dbea61fc3.png)
