### ISSUE TITLE
ClassNotFoundException when compiling

### ISSUE THREAD

**Issue by lostkhaos** [bugdone/headshotbox#37]
After running `bower`, compiling demoinfogo, and running `lein run`, there's a `ClassNotFoundException` when looking for `CDataGCCStrike15_v2_MatchInfo` inside `Cstrike15Gcmessages` (referenced by `hsbox/demo.clj`):

[Compile Log](https://gist.github.com/lostkhaos/262db646685468cbe413)
[Lein Version](https://gist.github.com/lostkhaos/d544f0be9b40d7b05609)
[build.py Log (aborted after 3 minutes of no output)](https://gist.github.com/lostkhaos/eece3a46b7a361099616)

**Comment by bugdone** [comment]
I haven't tested with leiningen 1.x (I'm using 2.5.1)

**Comment by lostkhaos** [comment]
Confirmed 2.5.1 functions as expected! Cheers.
