### ISSUE TITLE
demos and highlights not playing when path has blanks

### ISSUE THREAD

**Issue by choseh** [bugdone/headshotbox#4]
apparantly blanks are not escaped properly

"Executing deferred playdemo: C:\Program"

steam://rungame/730/<foo>/+playdemo "C:\Program Files (x86)\Steam\SteamApps\common\Counter-Strike Global Offensive\csgo\replays\match730_003073078561616167050_1887076664_186.dem"

*edit* apparantly a chrome issue

**Comment by yoyosan** [comment]
Hey @choseh 

I found a fix. Basically, a relative path should be used.
In your case:
```
steam://rungame/730//+playdemo "replays/match730_003073078561616167050_1887076664_186.dem"
```

**Comment by choseh** [comment]
i made a symlink as a workaround, but thanks :+1:
