### ISSUE TITLE
doesnt scan new replays

### ISSUE THREAD

**Issue by simey420** [bugdone/headshotbox#41]
the program worked fine until one replay, then it stopped analyzing new demos. for older demos it still works fine.

this is what shows up when i start the program
![capture](https://cloud.githubusercontent.com/assets/10578231/7785148/416800e2-018b-11e5-85fd-bd1fc8fc3024.PNG)

**Comment by bugdone** [comment]
Please send me the log and sqlite files
c:/Users/\<user\>/.config/headshotbox/headshotbox.log
c:/Users/\<user\>/.config/headshotbox/headshotbox.sqlite

**Comment by simey420** [comment]
here 

http://teusku.cu.cc/headshotbox.7z

**Comment by danjono** [comment]
Same issue as above, use packrat to download demo's.
Her's a link to the logs.
https://www.dropbox.com/s/b6mkjgg1v4opyqw/headshotbox.rar?dl=0

**Comment by bugdone** [comment]
0.6.1 is out, please try it

**Comment by simey420** [comment]
works fine, thanks

**Comment by danjono** [comment]
Works fine for me too, many thanks!
