### ISSUE TITLE
Changes in account name is not reflected in headshotbox

### ISSUE THREAD

**Issue by reinZz** [bugdone/headshotbox#43]
After some of my friends and I have changed our steam account names, headshotbox continues to use a old name. Is this designed to work like this or can this be fixed?

**Comment by bugdone** [comment]
Steam data is refreshed once a day.

**Comment by reinZz** [comment]
But I have changed my steam name for a few weeks now and the name in headshotbox is still the old one

**Comment by bugdone** [comment]
Did you set a steam api key in settings?

**Comment by bugdone** [comment]
Closing due to lack of feedback.
