### ISSUE TITLE
Only show VAC badge if VAC.days < played against since

### ISSUE THREAD

**Issue by beig** [bugdone/headshotbox#44]
Because obviously you can't play versus an already VACed player.

**Comment by bugdone** [comment]
Good idea.

**Comment by beig** [comment]
Hello,

just saw that it still shows the VAD badge even is the ban is >1000 days old

![image](https://cloud.githubusercontent.com/assets/2438152/8077362/6b87e16c-0f55-11e5-9597-e917d96887c7.png)

Steam profile: http://steamcommunity.com/id/Raigik/

Is there even a timestamp in the demo? Or is the timestamp from the file-date?  'Cause I couldn't find one with grep.

**Comment by bugdone** [comment]
Probably a caching issue, same as #55

**Comment by bugdone** [comment]
Was this a caching issue?
