### ISSUE TITLE
Make it possible to search by player name/Steam ID

### ISSUE THREAD

**Issue by coloco21** [bugdone/headshotbox#45]
For instance, if I see a VAC'd player in my recently played with people on Steam, I'd like to be able to search for his name or steam ID to find the matching demo(s).

I'd make a pull request but I'd need to learn functional programming and Clojure first.

**Comment by bugdone** [comment]
If you know his steamid64, you can just go to `http://localhost:4000/index.html#/player/<steamid64>` to see all his demos.

**Comment by bugdone** [comment]
Shouldn't be needed with #51
