### ISSUE TITLE
A version for servers/publicity

### ISSUE THREAD

**Issue by Cludch** [bugdone/headshotbox#50]
Hey.

What about a version, which is thought to be visitable by the publicity?
I would like to see a version, where you can login via Steam and set, who can view the demos + stats.

Would be a nice tool to use in small eSport teams.
If you want, I could help a bit :)

**Comment by Schrubbii** [comment]
Well - theoretical you can give your friends your router's ip & open Port 4000 for your computer. That would allow others to get onto the overview. Watching demos would need them to download all the demos which is theoreticly possible if you make your demo-folder shared for "Everyone". All that would be to do on "client-side" (bugdone) would be to change the path of the link (The button to watch the demo) from local to ip-based.

**Comment by Cludch** [comment]
I know.
That's why I would like to have a server version.
I run it on my VPS, when we want to look at a few stats and afterwards I shutdown hsbox.

Because of changing settings, I would like to see a server version.

**Comment by lukealford** [comment]
Maybe this will be possible come closer to 1.0, currently it's more about fleshing the features out. Building it as a on-line app shouldn't be too much change to the code, from my view all it really needs is a user system & roles to limit access and changes.

An idea I had a couple of days back was maybe we could integrate drop-box as well for demo's that was if it was to go on-line, just makes it easy in terms of downloading a demo and having dropbox auto sync it to your account. At the end of the day it all comes down to @bugdone as he has final say :+1:

**Comment by Cludch** [comment]
I like your idea with the Dropbox Sync :)

**Comment by Schrubbii** [comment]
Well - free Dropbox got a limit of 2GB. Thats enough space for like 68 demos (calculating 30MB/file). If he would get the upgrade for 1TB (9,99€/Month), it would mean enough space for 33333 but who would pay about 10€/Month just to have your demos saved in the net? I've extracted the .jar & changed the .html-file so it doesnt display the settings at all while I made also changed the settings-file so the only1 who could access it in any way is my local computer.

**Comment by lukealford** [comment]
free is enough for a small amount, but as you said no one would buy dropbox just for demo's unless they are well off, saying that a lot of people may already have dropbox subs for other reasons. 

I was only using dropbox as an example, I'm sure a solution could be done with out it.

**Comment by bugdone** [comment]
Hi!

Please try 0.8 and tell me what you think.

**Comment by Cludch** [comment]
Awesome update, thanks a lot!
