### ISSUE TITLE
Download link is broken on the website.

### ISSUE THREAD

**Issue by RicardoAlmeida25** [bugdone/headshotbox#52]
Currently, the download button on the website is broken.

Link for Windows: https://github.com/bugdone/headshotbox/releases/download/0.7.0/headshotbox-0.7.0-win.zip

Link for Linux: https://github.com/bugdone/headshotbox/releases/download/0.7.0/headshotbox-0.7.0-linux.zip

**Comment by bugdone** [comment]
fixed, thanks!
