### ISSUE TITLE
The search feature is not working

### ISSUE THREAD

**Issue by TGGHD** [bugdone/headshotbox#53]
The search feature does nothing when I attempt to search anything for example:  3k

**Comment by bugdone** [comment]
Send me the headshotbox.sqlite and headshotbox.log files

**Comment by TGGHD** [comment]
I restarted my computer, and got it to start working :+1:

**Comment by bugdone** [comment]
Maybe you HeadshotBox was closed when you were searching.

**Comment by bugdone** [comment]
Closing this one, if happens again please reopen.
