### ISSUE TITLE
Match outcome always "Draw!"

### ISSUE THREAD

**Issue by ben3005** [bugdone/headshotbox#54]
The match outcome always says "Draw!"
![bug cap](https://cloud.githubusercontent.com/assets/2751508/8020293/5a651496-0c6b-11e5-8fac-51a62e2a2f43.PNG)

**Comment by bugdone** [comment]
What browser are you using? (the play button to the left of Highlights seems broken too)

**Comment by ben3005** [comment]
Google Chrome v43 - apparently it was a caching issue (i was using v0.4 last) it is not giving the wrong outcomes anymore
