### ISSUE TITLE
New Version doesn't show CT Wins/T Wins 

### ISSUE THREAD

**Issue by beig** [bugdone/headshotbox#55]
Instead it only shows 

Draw! : (:; :)

for every game.

Version is 0.7

**Comment by TimHi** [comment]
Does your demoinfogo still crash? Because mine does and i also see only draw

**Comment by beig** [comment]
On Linux it does not crash for me

**Comment by bugdone** [comment]
Might be a caching issue. Try ctrl+f5 in browser.

**Comment by bugdone** [comment]
Was this a caching issue?

**Comment by TimHi** [comment]
I cant remember it magicly started working again, might have been one. Or it was a problem with the demoinfogo crashing which i fixed by deleting the specific demo.

**Comment by bugdone** [comment]
If the demoinfogo crashes then no data gets into Headshot Box from that demo so I doubt that deleting the demo fixed this issue.
I'm closing this issue.If it happens again, please reopen.
