### ISSUE TITLE
demoinfogo.exe stopped working

### ISSUE THREAD

**Issue by TimHi** [bugdone/headshotbox#56]
First of: here is the log http://pastebin.com/k2EXJnZR
I'm using the latest version and tried different compability settings. After demoinfogo crashes i can still see the players list but every match is marked as a draw. 
I currently have 210 demos which are 2,1 gb so i dont know if thats too much?

**Comment by bugdone** [comment]
Can you give me the full log? (might help to know if you used a previous version before and if the db migration worked ok). Also the headshotbox.sqlite file would help.
No, 200 demos is not a lot. I have 470 demos / 13gb.

**Comment by TimHi** [comment]
I've moved my demos to another partition -> same error. I deleted the demo which made trouble and it's working again now. 
Not sure what the problem with that specifc demo was.

**Comment by bugdone** [comment]
By
> every match is marked as a draw. 

you mean the text displayed at the top of the scoreboard for that demo (issue #55)?

Can you please send me that demo?

Also, how did you come by "demoinfogo.exe stopped working"? Did you try to run it manually?

Since this happened, have you downloaded other demos (if yes, did Headshot Box work correctly)?

**Comment by TimHi** [comment]
Yep i had the same issue, works now again with the new UI, guess i stil had the old site in my cache or something. 

>Also, how did you come by "demoinfogo.exe stopped working"? Did you try to run it manually?

I ran the .bat, while processing the demo it said demoinfogo crashed. 


https://drive.google.com/file/d/0B3FrnSHmvBifdjdlU2pSMVZPclU/view?usp=sharing  Here is the demo that causes the crash.

**Comment by bugdone** [comment]
It looks like I need your permission to download that file on google drive.

You mean a window popped up like this?
<img src="http://windows-exe-errors.com/wp-content/uploads/windows-explorer-has-stopped-working.gif" height="150"/>

**Comment by TimHi** [comment]
![crash](https://cloud.githubusercontent.com/assets/10931525/8110946/1d5217be-105f-11e5-9d4a-0aa884457aee.png)

This is the error message, check if the drive link is working now.

**Comment by wadum** [comment]
I think this happens because the download of a .dem file might be only partially complete when headshotbox tries to analyze it. This occurs with your packrat script if headshotbox is open at the same time-

**Comment by bugdone** [comment]
The issue here is that the demo parsing code goes into an infinite loop which keeps allocating memory until it requests so much that it crashes.

**Comment by wadum** [comment]
Weird. I got the same error quite frequently, untill i changed packrat to download the file to a temporary filename, and rename it afterwards.

```python
download_bz2(link, dest + ".tmp")
os.rename(dest + ".tmp", dest)
```

**Comment by bugdone** [comment]
Yes, probably the problem usually comes from trying to parse incomplete demos (currently if the file is not modified for more than 5 seconds, Headshot Box tries to parse it). I think your fix is a pretty good idea and should be in packrat. I'd merge your pull request if you'd send one.

But for the demo he shared with me, the problem lies in the demoinfogo code.

**Comment by bugdone** [comment]
I tried to watch the demo with `playdemo` in csgo, but it doesn't work.

    WARNING: demo network protocol 13483 differs, engine version is 13493 
    WARNING: Server demo version 13483, client version 13493.
    ***String table CRC mismatch, may need to rebuild bsp if model oddities occur!
    Host_EndGame: Error reading demo message data.

I don't think it's worth investigating, it's probably a corrupt demo.
