### ISSUE TITLE
User game ban status is not updated (cached?)

### ISSUE THREAD

**Issue by domrin123** [bugdone/headshotbox#57]
Game ban status appears to be cached, so if a player is banned after the initial steam api call is made to get the player status, the status is never updated.

Could there maybe be a cooldown so that the ban status is re fetched if the current status is a number of minutes old?

**Comment by bugdone** [comment]
Steam data is cached for 24 hours.

**Comment by domrin123** [comment]
Ah ok. Thanks. I had not examined the code enough. Do you think it is within scope to have some way of refreshing the data for a game/clearing cache?

**Comment by bugdone** [comment]
Options:
* have the caching interval configurable in hours
* have a refresh button

Or both. What do you think?

**Comment by domrin123** [comment]
I think a refresh button might be more intuitive. I guess no matter how low the caching interval is, people are going to want to have the power to see the most up to date information. 

I suppose if you had the option to change the interval, then you could set it to 0 to have a similar effect to refreshing, but every time you click on a match. 

My only issue with a refresh button would be that it would have to be explicit about what it does. Some may assume that a refresh button would reanalyse the demo altogether. I guess that's more a UX issue than anything. I think for simplicity it could look something like this: 

http://imgur.com/L095Xrw

**Comment by bugdone** [comment]
Implemented #162 instead.
