### ISSUE TITLE
Final Score is wrong

### ISSUE THREAD

**Issue by Schrubbii** [bugdone/headshotbox#60]
Thats how HeadshotBox displays the game:
http://prntscr.com/7jn6mu

Thats how CS:GO displays it:
http://prntscr.com/7jn6us

16:13 & 16:14?

Furthermore the stats are also incorrect.
Why does this happen?

**Comment by bugdone** [comment]
It looks like it missed a round in the first half. Can you please send me the demo?

**Comment by Schrubbii** [comment]
http://selection43.de/replays/match730_003080907883269849248_1795239703_136.dem

Its online in about 5 Mins. Got some more of these demos where I get less kills/assists/deaths cause of some missing rounds.

**Comment by bugdone** [comment]
This is a nasty one. It seems that the round_end event sometimes is missing.
I could try to hack this by trying to use other events to figure out the missing information, but it still won't work always and it would increase the code's complexity. This is why I'm reluctant to do this hack.

Can you tell me how many demos are in this situation? Or can you send me the headshotbox.sqlite file?

**Comment by semencmoz** [comment]
i had demo with same issue awile ago. game ended up 16-14, but score was shown 15-14. if i find backup, i'll leave it here.
