### ISSUE TITLE
Java 8 doesn't seem to work

### ISSUE THREAD

**Issue by bionicsheep** [bugdone/headshotbox#62]
Finally caved an updated since the stupid update notification came on practically daily basis, broke demo parsing, went back to 7 and all is well. Just figured I would let you know in case you didn't know

**Comment by bugdone** [comment]
Can you give me the logs? Also, which os and exact java version were you using?
(I use java 1.8.0_45 on Linux and it works fine)

**Comment by bugdone** [comment]
closing due to lack of feedback
