### ISSUE TITLE
Google Chrome display bug

### ISSUE THREAD

**Issue by danjono** [bugdone/headshotbox#63]
This only seems to effect Google Chrome as Internet Explorer appears fine.
http://i.imgur.com/lZQETnY.png

**Comment by bugdone** [comment]
I can't reproduce this in Chrome 43 either on Linux or Windows.
Is it still happening?

**Comment by danjono** [comment]
No, this seems to have fixed itself even though I had tried deleting cache and temp files before.

**Comment by allanbrault** [comment]
I had the same problem, it was the "style" cookie that was set to null and broke the style, to fix you just need to select one of the theme in the settings

**Comment by bugdone** [comment]
Thanks @allanbrault , good catch.
