### ISSUE TITLE
Unknown Demo Type?

### ISSUE THREAD

**Issue by bm92** [bugdone/headshotbox#65]
2015-Jul-15 01:59:29 +1000 Unknown-PC ERROR [hsbox.indexer] - Cannot parse demo
C:\Users\BC\Pictures\Demos\Demo1.dem
2015-Jul-15 01:59:29 +1000 Unknown-PC ERROR [hsbox.indexer] -
         ←[37mhsbox.core.main←[m  ←[32m                ←[m
                     ←[37m...←[m  ←[32m                ←[m
        ←[33mhsbox.core/←[1;33m-main←[m  ←[32m   core.clj:  43←[m
       ←[33mhsbox.indexer/←[1;33mrun←[m  ←[32mindexer.clj:  94←[m
  ←[33mhsbox.indexer/←[1;33madd-demo←[m  ←[32mindexer.clj:  54←[m
←[33mhsbox.demo/←[1;33mget-demo-info←[m  ←[32m   demo.clj: 201←[m
←[1;31mjava.lang.Exception←[m: ←[3mUnknown demo type←[m

Any idea?

**Comment by bugdone** [comment]
Please sent it to me.

**Comment by bm92** [comment]
Thanks for the fast reply. We have roughly 100 demos from a local LAN, none
seem to be loading. I've followed your instructions on the site and tried
to self troubleshoot but I can't seem to get them to parse.
These were from a local LAN server using WARMOD, so I'm unsure if that's
why it's not working and the MatchMaking ones are.

http://www.filedropper.com/deoverpass-capital-vs

**Comment by bugdone** [comment]
Currently only faceit, mm and esea demos are supported.
The "demo type" (one of the 3 listed above) is detected by some heuristics related to the name of the server and gotv bots.

Making it work for every demo is, sadly, an impossible problem. The demos are just a stream of events. Making sense which events count and which don't depends upon lots of factors.
Examples:
* warmup rounds (in ESEA there's more than 1 warmup round)
* knife rounds
* admins decide that a rounds needs to be replayed
* game split in multiple demos (which seems to be the case with your demo)
* sometimes the ebot gets bugged and the score is wrong

So what I did was to look for some patterns for the 3 very common types of demos people have and wrote some heuristics to make them work. And it's still not perfect as it seems that some events may be missing...

I'm closing this with wontfix. It would be great to have the perfect parser, but it's simply not possible.

There are only 2 possibilities here:
* either you adopt the plugins/rules/whatever the big leagues are using and you can use the tools people wrote for them
* or have someone write code specifically for your problem
