### ISSUE TITLE
Add checkbox to exclude some demos  from statistics.

### ISSUE THREAD

**Issue by semencmoz** [bugdone/headshotbox#67]
possible usages: 
1) you can track more recent statistics, and not include older stats without deleting demo files
2) you can sort statistics by certain scenarios. like you can decide to exclude all first games in day as "warmup - games"
3) you can exclude games where players had disconnects/network issues/leaves etc

**Comment by bugdone** [comment]
I don't want to implement this.
For 1) you can use the date filter.
I don't like 2). The warmup game excluding is just a way to make yourself feel better by selecting games you did good in. If you happen to have a great first game in a day, you wouldn't exclude it.
3) is understandable, but the amount of games with issues should be small and not affect the overall stats.
