### ISSUE TITLE
Add 17csgo support

### ISSUE THREAD

**Issue by Oklahomawhore** [bugdone/headshotbox#69]
Writer pls add 17csgo support it's a "chinese ESEA". Pls I love headshotbox I can't live without it pls. The official website for 17csgo is http://www.17csgo.com     Thank you very much ^.^

**Comment by 0BuRner** [comment]
Give a link to one or more demo recorded by 17csgo so it will be easier.

**Comment by bugdone** [comment]
closing due to lack of feedback
