### ISSUE TITLE
Not showing players or demos

### ISSUE THREAD

**Issue by WuaghhhhXMA** [bugdone/headshotbox#7]
Hey, downloaded the tool on my notebook, where cs isn't installed, have some demos saved though.
Opened the .bat, didn't find the demos ofc. Went to http://127.0.0.1:4000 changed the directory to my demo archive (at least I think so), wrote down my steam web api key, updated (settings did really save). Opened the .bat again, still no players etc. on the site :(

2015-Mai-08 11:51:26 +0200 XMAsTablet INFO [hsbox.core] - HeadshotBox  0.3.0
2015-Mai-08 11:51:27 +0200 XMAsTablet INFO [hsbox.version] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
2015-Mai-08 11:51:27 +0200 XMAsTablet ERROR [hsbox.core] - 
                              [37mjava.lang.Thread.run[m  [32m  [m
         [37msun.nio.fs.WindowsWatchService$Poller.run[m  [32m  [m
         [37msun.nio.fs.AbstractPoller.processRequests[m  [32m  [m
[37msun.nio.fs.WindowsWatchService$Poller.implRegister[m  [32m  [m
         [37msun.nio.fs.WindowsException.asIOException[m  [32m  [m
[37msun.nio.fs.WindowsException.translateToIOException[m  [32m  [m
[1;31mjava.nio.file.NoSuchFileException[m: [3mC:\Program Files (x86)\Steam\SteamApps\common\Counter-Strike Global Offensive\csgo\replays[m
    [1mfile[m: "C:\\Program Files (x86)\\Steam\\SteamApps\\common\\Counter-Strike Global Offensive\\csgo\\replays"

2015-Mai-08 11:51:27 +0200 XMAsTablet DEBUG [hsbox.version] - Latest version 0.3.0
2015-Mai-08 11:53:25 +0200 XMAsTablet INFO [hsbox.core] - HeadshotBox  0.3.0
2015-Mai-08 11:53:25 +0200 XMAsTablet INFO [hsbox.version] - Checking latest version on https://raw.githubusercontent.com/bugdone/headshotbox/master/latest-windows-version
2015-Mai-08 11:53:25 +0200 XMAsTablet ERROR [hsbox.core] - 
                              [37mjava.lang.Thread.run[m  [32m  [m
         [37msun.nio.fs.WindowsWatchService$Poller.run[m  [32m  [m
         [37msun.nio.fs.AbstractPoller.processRequests[m  [32m  [m
[37msun.nio.fs.WindowsWatchService$Poller.implRegister[m  [32m  [m
         [37msun.nio.fs.WindowsException.asIOException[m  [32m  [m
[37msun.nio.fs.WindowsException.translateToIOException[m  [32m  [m
[1;31mjava.nio.file.NoSuchFileException[m: [3mC:\Program Files (x86)\Steam\SteamApps\common\Counter-Strike Global Offensive\csgo\replays[m
    [1mfile[m: "C:\\Program Files (x86)\\Steam\\SteamApps\\common\\Counter-Strike Global Offensive\\csgo\\replays"

2015-Mai-08 11:53:26 +0200 XMAsTablet DEBUG [hsbox.version] - Latest version 0.3.0
2015-Mai-08 11:53:41 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2015-Mai-08 11:54:59 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2015-Mai-08 11:57:17 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2015-Mai-08 12:06:46 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2015-Mai-08 12:10:28 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2015-Mai-08 12:14:33 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2015-Mai-08 13:14:15 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2015-Mai-08 13:16:30 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

2015-Mai-08 13:23:45 +0200 XMAsTablet ERROR [hsbox.core] - 
                                            [37mhsbox.core.main[m  [32m                                [m
                                                        [37m...[m  [32m                                [m
                                           [33mhsbox.core/[1;33m-main[m  [32m                   core.clj:  21[m
                               [33mring.adapter.jetty/[1;33mrun-jetty[m  [32m                  jetty.clj: 103[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
                    [37morg.eclipse.jetty.server.Server.doStart[m  [32m                Server.java: 292[m
   [37morg.eclipse.jetty.util.component.AbstractLifeCycle.start[m  [32m     AbstractLifeCycle.java:  64[m
[37morg.eclipse.jetty.server.nio.SelectChannelConnector.doStart[m  [32mSelectChannelConnector.java: 265[m
         [37morg.eclipse.jetty.server.AbstractConnector.doStart[m  [32m     AbstractConnector.java: 316[m
   [37morg.eclipse.jetty.server.nio.SelectChannelConnector.open[m  [32mSelectChannelConnector.java: 187[m
                        [37msun.nio.ch.ServerSocketAdaptor.bind[m  [32m                                [m
                    [37msun.nio.ch.ServerSocketChannelImpl.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                        [37msun.nio.ch.Net.bind[m  [32m                                [m
                                       [37msun.nio.ch.Net.bind0[m  [32m                                [m
[1;31mjava.net.BindException[m: [3mAddress already in use: bind[m

**Comment by hyouge** [comment]
My log looks about the same, and I'm guessing it has something to do with the "Address already in use" part at the end.

**Comment by bugdone** [comment]
It looks like initially it tried to get the demos in "C:\Program Files (x86)\Steam\SteamApps\common\Counter-Strike Global Offensive\csgo\replays" and it failed.
Then you started it again and it could not run since it was already open (Address already in use: bind tells you that it could not start the web server)
I need to make it single instance.

**Comment by WuaghhhhXMA** [comment]
Yeah, seems to be, that the task didn't close correct. After rebooting, seems to work now. Thanks for your feedback
