### ISSUE TITLE
HSbox doesnt work on Windows 10/

### ISSUE THREAD

**Issue by GlebkaF** [bugdone/headshotbox#70]
When i trying to execute headshotbox.bat i got this screen:
![win10](https://cloud.githubusercontent.com/assets/8992139/9020825/32e74bf0-382b-11e5-8def-7bafe1a02f8b.png)
It says that : "Cant execute this application on your PC.To find the version for your computer, contact the publisher of the application
If i'am trying to execute headshotbox.bat via CMD i dont get anything:
![win10](https://cloud.githubusercontent.com/assets/8992139/9020832/b94d1b48-382b-11e5-8229-e3b5d2c4e2e1.png)
But it works 2 day ago, when i just installed windows 10.

**Comment by bugdone** [comment]
Please send me the logs.

**Comment by GlebkaF** [comment]
Cant attach log to the issue, so: https://dropmefiles.com/Ipcf0

**Comment by bugdone** [comment]
I assume it's a Java issue (you either don't have Java installed or the version you installed doesn't work on Windows 10).

**Comment by GlebkaF** [comment]
It didnt work without java, it works after i installed java. Java has not been updated since I installed it, but hsbox is not working now.

**Comment by bugdone** [comment]
What Java version do you have now (run `java -version`) and what Java version were you using prior to installing Windows 10?

(Maybe it's the same issue as  #62)

**Comment by GlebkaF** [comment]
C:\Users\Глеб>java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) Client VM (build 25.51-b03, mixed mode)
You did not understand me, it work on windows 10! With the same java version.

**Comment by bugdone** [comment]
Since it suddenly stopped working, it must be a nasty weird issue (eg. files got corrupted, java or windows got some update, etc). I don't really know how to debug this since I don't have windows 10 to try to reproduce this.

The only things I can think of is to check that the jar file is not corrupted (re-download it) and maybe try java7.

**Comment by GlebkaF** [comment]
oh, i trying to extract old files from zip archive, but it dont helped. I downloaded a new arhive from github, and it works now, thank you for help :)
