### ISSUE TITLE
Clutch % on the overview not updating/calculating properly?

### ISSUE THREAD

**Issue by zergl64** [bugdone/headshotbox#71]
So unless I'm misunderstanding something, Clutch% stat should consist of all the 1v1 rounds won out of all attempts.

But if I'm searching 1v1 in the Search field, I get way more results than in the mouseover tooltip on the Clutch% stat.

Clutch%: 70.94 (83/117), first number in brackets should be the 1v1 rounds won, right?

Searching for 1v1 rounds (which only displays won 1v1 situations): 100+ results 

A friend's stats with 98 demos on my Headshotbox:

Clutch%: 68.00 (34/50)

Searching for 1v1: 56 rounds

This is consistent across all my friends. 1v1 Rounds won in the search is consistently higher than the rounds won in the Clutch% tooltip.

**Comment by zergl64** [comment]
Screenshots:

![my stats](https://cloud.githubusercontent.com/assets/12449605/9116850/d68cb06c-3c66-11e5-838e-8583da22b30c.png)

![friend stats](https://cloud.githubusercontent.com/assets/12449605/9116893/10628172-3c67-11e5-9ff7-1b6a6fe39938.png)

All demos are standard Valve MM.

**Comment by bugdone** [comment]
There are two ways of getting in a 1v1 situation; you are either:
* in a 2v1 and your teammate dies
* in a 1v2 and you kill one of them

The Clutch% takes into account only the first option. I chose here the same definition as hltv.org.

The search takes both into account. Same as the kills search, they are treated as >=, not =. So actually searching for 1v1 will find 1v5 rounds also.

I admit this is confusing. It's not mentioned in the search help.

Should I change the search to be strict?

**Comment by semencmoz** [comment]
I think you can just add link to HLTV definition in clutch% popup. also i prefer to see both values in general statistics - 1v1 clutch where was 2v1 situation and your teammate died, and 1v1 situation where you killed most of the oponents by yourself and managed to take 1v4 round.

**Comment by zergl64** [comment]
Ah well, that explains it.

I was aware of how the search behaves, but HLTV's defninition is a bit counterintuitive (1vX situations that I bring down to 1v1 are still clutch attempts *shrug*). Maybe a toggle in the settings between HLTV's definition and the less strict one on top of an explanation in the tooltip?

**Comment by bugdone** [comment]
There's no definition on hltv.org to link to. I added more explanations in search round and near the clutch rating.
There's really no point in having both definitions as the more general definition would yield very low percentages (there's a reason why you can see the win% for 1v1 but only the number of rounds won for the rest of the clutches on hltv.org).
