### ISSUE TITLE
Doesn't work on Windows 10 (Assertion Error)

### ISSUE THREAD

**Issue by leteamfivestar** [bugdone/headshotbox#72]
Hey,

I tried using HS Box on Windows 10, but it doesnt seem to parse any demos. In the log file,
there are several incidents of "[1;31mjava.lang.AssertionError[m: [3mAssert failed: (zero? (:exit proc))[m", one for each demo file, to be exact.

Thanks for the help already!

**Comment by bugdone** [comment]
Did you install the Visual C++ Redistributable Packages for VS 2013?

**Comment by leteamfivestar** [comment]
I did now, and it works. Thanks!
