### ISSUE TITLE
Demo list entries spread to multiple lines / CSS breaks down

### ISSUE THREAD

**Issue by boozoclown** [bugdone/headshotbox#73]
Using firefox on a multi-monitor setup (1680x1050 + 1920x1080 side by side) entries on the demo list get spread over multiple lines. Just realized while testing that making the window even smaller leads to 3 lines, then the UI kind of breaks down, then it looks all good again.

![hsb1](https://cloud.githubusercontent.com/assets/13807490/9288070/d4ecbda4-4334-11e5-8d0c-2f3e9ba07235.jpg)

![hsb2](https://cloud.githubusercontent.com/assets/13807490/9288071/d79e6c28-4334-11e5-844b-ca5ff3a21d24.png)

![hsb3](https://cloud.githubusercontent.com/assets/13807490/9288077/2da76d9a-4335-11e5-887e-08cd5c46c616.png)

![hsb4](https://cloud.githubusercontent.com/assets/13807490/9288078/3098f578-4335-11e5-96b0-65ce21e168f9.png)

**Comment by bugdone** [comment]
I improved it a bit, but it's still far from perfect.
You can check out a preview of the latest code here: http://hsbox-ezstats.rhcloud.com (beware slow as dirt hosting)

**Comment by boozoclown** [comment]
The random popin from the menu seems to be gone, but the width behaviour seems pretty much unchanged for me. I know less about CSS than you claim to do, but I believe the first break happens when the Watch-column is compressed to a width below what the 3 buttons plus the spacing between them is (103.something px here). The other space-wise "constricted" part are the rank symbols, might be that too.
Next snap happens when the Date column goes below 120px, lines stay the same here but the text in the Date-column jumps from center- to left-aligned (visually, CSS says left no matter what).

I don't know if this helps tbh. but I'm afraid I can't provide much more info without diving into learning some CSS ;)
