### ISSUE TITLE
OpenId Authentication broken?

### ISSUE THREAD

**Issue by executor513** [bugdone/headshotbox#74]
Whenever i try to login to steam while making the site public via OpenID, i get this error. 

Will add a video recreating this error tomorrow.

2015-Aug-19 20:47:55 -0700 Forvana-PC ERROR [hsbox.handler] - 
[37m java.lang.Thread.run[m
[37m org.eclipse.jetty.util.thread.QueuedThreadPool$3.run[m  
[32m QueuedThreadPool.java:  543[m
[37m org.eclipse.jetty.util.thread.QueuedThreadPool.runJob[m  
[32m QueuedThreadPool.java:  608[m
[37m org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run[m  
[32m SelectChannelEndPoint.java:   52[m
[37m org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle[m  
[32m SelectChannelEndPoint.java:  668[m
[37m org.eclipse.jetty.server.AsyncHttpConnection.handle[m  
[32m AsyncHttpConnection.java:   82[m
[37m org.eclipse.jetty.http.HttpParser.parseAvailable[m  
[32m HttpParser.java:  240[m
[37m org.eclipse.jetty.http.HttpParser.parseNext[m  
[32m HttpParser.java:  865[m
[37m org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content[m  
[32m AbstractHttpConnection.java: 1005[m
[37m org.eclipse.jetty.server.AbstractHttpConnection.content[m  
[32m AbstractHttpConnection.java:  944[m
[37m org.eclipse.jetty.server.AbstractHttpConnection.handleRequest[m  
[32m AbstractHttpConnection.java:  486[m
[37m org.eclipse.jetty.server.Server.handle[m  
[32m Server.java:  369[m
[37m org.eclipse.jetty.server.handler.HandlerWrapper.handle[m  
[32m HandlerWrapper.java:  116[m
[37m ring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle[m
[33m ring.adapter.jetty/proxy-handler/[1;33mfn[m  
[32m jetty.clj:   20[m
[33m ring.middleware.session/wrap-session/[1;33mfn[m  
[32m session.clj:   98[m
[33m ring.middleware.flash/wrap-flash/[1;33mfn[m  
[32m flash.clj:   35[m
[33m ring.middleware.multipart-params/wrap-multipart-params/[1;33mfn[m  
[32m multipart_params.clj:  118[m
[33m ring.middleware.params/wrap-params/[1;33mfn[m  
[32m params.clj:   64[m
[33m ring.middleware.nested-params/wrap-nested-params/[1;33mfn[m  
[32m nested_params.clj:   84[m
[33m ring.middleware.keyword-params/wrap-keyword-params/[1;33mfn[m  
[32m keyword_params.clj:   35[m
[33m hsbox.handler/wrap-exception/[1;33mfn[m  
[32m handler.clj:  123[m
[33m cemerick.friend/authenticate/[1;33mfn[m  
[32m friend.clj:  260[m
[33m cemerick.friend/[1;33mauthenticate*[m  
[32m friend.clj:  247[m
[33m cemerick.friend/[1;33mauthenticate-request[m  
[32m friend.clj:  238[m
[33m clojure.core/[1;33msome[m  
[32m core.clj: 2515[m
[33m cemerick.friend/authenticate-request/[1;33mfn[m  
[32m friend.clj:  238[m
[33m cemerick.friend.openid/workflow/[1;33mfn[m  
[32m openid.clj:  118[m
[33m cemerick.friend.openid/[1;33mhandle-init[m  
[32m openid.clj:   54[m
[37m ...
[37m org.openid4java.consumer.ConsumerManager.authenticate[m  
[32m ConsumerManager.java: 1071[m
[37m org.openid4java.message.AuthRequest.createAuthRequest[m  
[32m AuthRequest.java:  101[m
[37m org.openid4java.message.AuthRequest.validate
[32m AuthRequest.java:  354[m
[1;31m org.openid4java.message.MessageException[m: [3m0x301: Realm verification failed (2) for: [Personal IPv4] [m
[1m errorCode[m: 769

**Comment by bugdone** [comment]
Please tell me the URL you use to access headshotbox and what URL you passed to --openid-realm (or email the details if you're not comfortable posting it here).

**Comment by bugdone** [comment]
Closing due to lack of feedback.
