### ISSUE TITLE
Replace weapons game name by their real name

### ISSUE THREAD

**Issue by KowalskiThomas** [bugdone/headshotbox#76]
This would be better with "P250" rather than "p250", "AK-47" instead of "ak47", "Incendiary or Molotov" instead of "inferno"...
http://puu.sh/k7K0l/6053bfd8b0.png

**Comment by bugdone** [comment]
I haven't figured out a way to do this without either:
* having 2 columns in the weapon stats tab (one for the name and one for search keyword)
* having the list of guns with their keywords again in the search round help

**Comment by KowalskiThomas** [comment]
I didn't really understand your answer to be honest, but why don't you do something like having the real name, and then having the id of the span or the <p> set to the in game name ?

**Comment by bugdone** [comment]
The problem I had was not a technical one, but from a UI standpoint.
Having 2 columns in the weapons tab seemed kinda ugly/weird. Having the table again in the search help box seemed silly.

Anyway, I'll go with @clugg's implementation. Having two tables is insane.
