### ISSUE TITLE
Stops working when adding too many demos for an individual player

### ISSUE THREAD

**Issue by Robbert-jansen** [bugdone/headshotbox#8]
http://imgur.com/a/53U8M

as you can see it stops working if you add too many demos for a single player

**Comment by Robbert-jansen** [comment]
searching does still work

http://puu.sh/hFMST/68d3bee8fb.png

**Comment by jayd243** [comment]
I'm getting this issue too. It seems to happen once a player has 120-150+ demos parsed.
