### ISSUE TITLE
API not refreshing

### ISSUE THREAD

**Issue by Mo0shi** [bugdone/headshotbox#86]
Unable to get new data from steam ids.
New avatars no longer download, and vac ban status is frozen.
This has been occuring for the last 10 days.
Java errors from log:
ERROR [hsbox.handler] - 
                                                                     [37mjava.lang.Thread.run[m  [32m                                          [m
                                     [37morg.eclipse.jetty.util.thread.QueuedThreadPool$3.run[m  [32m               QueuedThreadPool.java:  543[m
                                    [37morg.eclipse.jetty.util.thread.QueuedThreadPool.runJob[m  [32m               QueuedThreadPool.java:  608[m
                                     [37morg.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run[m  [32m          SelectChannelEndPoint.java:   52[m
                                    [37morg.eclipse.jetty.io.nio.SelectChannelEndPoint.handle[m  [32m          SelectChannelEndPoint.java:  668[m
                                      [37morg.eclipse.jetty.server.AsyncHttpConnection.handle[m  [32m            AsyncHttpConnection.java:   82[m
                                         [37morg.eclipse.jetty.http.HttpParser.parseAvailable[m  [32m                     HttpParser.java:  235[m
                                              [37morg.eclipse.jetty.http.HttpParser.parseNext[m  [32m                     HttpParser.java:  644[m
            [37morg.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete[m  [32m         AbstractHttpConnection.java:  995[m
                           [37morg.eclipse.jetty.server.AbstractHttpConnection.headerComplete[m  [32m         AbstractHttpConnection.java:  933[m
                            [37morg.eclipse.jetty.server.AbstractHttpConnection.handleRequest[m  [32m         AbstractHttpConnection.java:  486[m
                                                   [37morg.eclipse.jetty.server.Server.handle[m  [32m                         Server.java:  369[m
                                   [37morg.eclipse.jetty.server.handler.HandlerWrapper.handle[m  [32m                 HandlerWrapper.java:  116[m
[37mring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle[m  [32m                                          [m
                                                      [33mring.adapter.jetty/proxy-handler/[1;33mfn[m  [32m                           jetty.clj:   20[m
                                                  [33mring.middleware.session/wrap-session/[1;33mfn[m  [32m                         session.clj:   98[m
                                                      [33mring.middleware.flash/wrap-flash/[1;33mfn[m  [32m                           flash.clj:   35[m
                                [33mring.middleware.multipart-params/wrap-multipart-params/[1;33mfn[m  [32m                multipart_params.clj:  118[m
                                                    [33mring.middleware.params/wrap-params/[1;33mfn[m  [32m                          params.clj:   64[m
                                      [33mring.middleware.nested-params/wrap-nested-params/[1;33mfn[m  [32m                   nested_params.clj:   84[m
                                    [33mring.middleware.keyword-params/wrap-keyword-params/[1;33mfn[m  [32m                  keyword_params.clj:   35[m
                                                          [33mhsbox.handler/wrap-exception/[1;33mfn[m  [32m                         handler.clj:  130[m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                            core.clj:  132[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  626[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                             [33mcompojure.core/if-context/[1;33mfn[m  [32m                            core.clj:  198[m
                                                                         [33mhsbox.handler/[1;33mfn[m  [32m                         handler.clj:  124[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                        [33mring.middleware.cors/wrap-cors/[1;33mfn[m  [32m                            cors.clj:  150[m
                                                   [33mring.middleware.json/wrap-json-body/[1;33mfn[m  [32m                            json.clj:   35[m
                                               [33mring.middleware.json/wrap-json-response/[1;33mfn[m  [32m                            json.clj:   65[m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                            core.clj:  132[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  626[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                              [33mcompojure.core/if-method/[1;33mfn[m  [32m                            core.clj:   27[m
                                                               [33mcompojure.core/if-route/[1;33mfn[m  [32m                            core.clj:   41[m
                                                  [33mcompojure.core/wrap-route-middleware/[1;33mfn[m  [32m                            core.clj:  103[m
                                                             [33mcompojure.core/make-route/[1;33mfn[m  [32m                            core.clj:  113[m
                                                                         [33mhsbox.handler/[1;33mfn[m  [32m                         handler.clj:   85[m
                                                         [33mhsbox.steamapi/[1;33mget-steamids-info[m  [32m                        steamapi.clj:   43[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  624[m
                                                                         [33mclojure.core/[1;33mseq[m  [32m                            core.clj:  133[m
                                                                                      [37m...[m  [32m                                          [m
                                                                      [33mclojure.core/map/[1;33mfn[m  [32m                            core.clj: 2559[m
                                                [33mhsbox.steamapi/[1;33mget-steamids-info-from-api[m  [32m                        steamapi.clj:   18[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  624[m
                                                                                      [37m...[m  [32m                                          [m
                                                                  [33mwatt.core/method->fn/[1;33mfn[m  [32m                            core.clj:   51[m
                                                     [33mclj-http.client/wrap-unknown-host/[1;33mfn[m  [32m                          client.clj:  726[m
                                                             [33mclj-http.links/wrap-links/[1;33mfn[m  [32m                           links.clj:   50[m
                                                         [33mclj-http.cookies/wrap-cookies/[1;33mfn[m  [32m                         cookies.clj:  122[m
                                                           [33mclj-http.client/wrap-method/[1;33mfn[m  [32m                          client.clj:  624[m
                                                    [33mclj-http.client/wrap-nested-params/[1;33mfn[m  [32m                          client.clj:  707[m
                                                      [33mclj-http.client/wrap-form-params/[1;33mfn[m  [32m                          client.clj:  683[m
                                                     [33mclj-http.client/wrap-content-type/[1;33mfn[m  [32m                          client.clj:  512[m
                                                  [33mclj-http.client/wrap-accept-encoding/[1;33mfn[m  [32m                          client.clj:  536[m
                                                           [33mclj-http.client/wrap-accept/[1;33mfn[m  [32m                          client.clj:  522[m
                                                       [33mclj-http.client/wrap-exceptions/[1;33mfn[m  [32m                          client.clj:  164[m
                                                  [33mclj-http.client/wrap-output-coercion/[1;33mfn[m  [32m                          client.clj:  398[m
                                        [33mclj-http.client/wrap-additional-header-parsing/[1;33mfn[m  [32m                          client.clj:  494[m
                                                   [33mclj-http.client/wrap-input-coercion/[1;33mfn[m  [32m                          client.clj:  445[m
                                                    [33mclj-http.client/wrap-decompression/[1;33mfn[m  [32m                          client.clj:  284[m
                                                        [33mclj-http.client/wrap-redirects/[1;33mfn[m  [32m                          client.clj:  212[m
                                                              [33mclj-http.client/wrap-url/[1;33mfn[m  [32m                          client.clj:  717[m
                                                        [33mclj-http.client/wrap-user-info/[1;33mfn[m  [32m                          client.clj:  617[m
                                                            [33mclj-http.client/wrap-oauth/[1;33mfn[m  [32m                          client.clj:  604[m
                                                       [33mclj-http.client/wrap-basic-auth/[1;33mfn[m  [32m                          client.clj:  594[m
                                                     [33mclj-http.client/wrap-query-params/[1;33mfn[m  [32m                          client.clj:  577[m
                                                      [33mclj-http.headers/wrap-header-map/[1;33mfn[m  [32m                         headers.clj:  138[m
                                                   [33mclj-http.client/wrap-request-timing/[1;33mfn[m  [32m                          client.clj:  751[m
                                                                                      [37m...[m  [32m                                          [m
                                                                    [33mclj-http.core/[1;33mrequest[m  [32m                            core.clj:  289[m
                                  [37morg.apache.http.impl.client.CloseableHttpClient.execute[m  [32m            CloseableHttpClient.java:  106[m
                                  [37morg.apache.http.impl.client.CloseableHttpClient.execute[m  [32m            CloseableHttpClient.java:   82[m
                                 [37morg.apache.http.impl.client.AbstractHttpClient.doExecute[m  [32m             AbstractHttpClient.java:  863[m
                               [37morg.apache.http.impl.client.DefaultRequestDirector.execute[m  [32m         DefaultRequestDirector.java:  446[m
                            [37morg.apache.http.impl.client.DefaultRequestDirector.tryConnect[m  [32m         DefaultRequestDirector.java:  611[m
                               [37morg.apache.http.impl.conn.ManagedClientConnectionImpl.open[m  [32m    ManagedClientConnectionImpl.java:  304[m
                 [37morg.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection[m  [32mDefaultClientConnectionOperator.java:  177[m
                             [37morg.apache.http.conn.scheme.PlainSocketFactory.connectSocket[m  [32m             PlainSocketFactory.java:  117[m
                                                                  [37mjava.net.Socket.connect[m  [32m                                          [m
                                                         [37mjava.net.SocksSocketImpl.connect[m  [32m                                          [m
                                                         [37mjava.net.PlainSocketImpl.connect[m  [32m                                          [m
                                                 [37mjava.net.AbstractPlainSocketImpl.connect[m  [32m                                          [m
                                        [37mjava.net.AbstractPlainSocketImpl.connectToAddress[m  [32m                                          [m
                                               [37mjava.net.AbstractPlainSocketImpl.doConnect[m  [32m                                          [m
                                          [37mjava.net.DualStackPlainSocketImpl.socketConnect[m  [32m                                          [m
                                               [37mjava.net.DualStackPlainSocketImpl.connect0[m  [32m                                          [m
[1;31mjava.net.ConnectException[m: [3mConnection timed out: connect[m

2015-Oct-31 01:51:03 +1000 Death ERROR [hsbox.handler] - 
                                                                     [37mjava.lang.Thread.run[m  [32m                                          [m
                                     [37morg.eclipse.jetty.util.thread.QueuedThreadPool$3.run[m  [32m               QueuedThreadPool.java:  543[m
                                    [37morg.eclipse.jetty.util.thread.QueuedThreadPool.runJob[m  [32m               QueuedThreadPool.java:  608[m
                                     [37morg.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run[m  [32m          SelectChannelEndPoint.java:   52[m
                                    [37morg.eclipse.jetty.io.nio.SelectChannelEndPoint.handle[m  [32m          SelectChannelEndPoint.java:  668[m
                                      [37morg.eclipse.jetty.server.AsyncHttpConnection.handle[m  [32m            AsyncHttpConnection.java:   82[m
                                         [37morg.eclipse.jetty.http.HttpParser.parseAvailable[m  [32m                     HttpParser.java:  235[m
                                              [37morg.eclipse.jetty.http.HttpParser.parseNext[m  [32m                     HttpParser.java:  644[m
            [37morg.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete[m  [32m         AbstractHttpConnection.java:  995[m
                           [37morg.eclipse.jetty.server.AbstractHttpConnection.headerComplete[m  [32m         AbstractHttpConnection.java:  933[m
                            [37morg.eclipse.jetty.server.AbstractHttpConnection.handleRequest[m  [32m         AbstractHttpConnection.java:  486[m
                                                   [37morg.eclipse.jetty.server.Server.handle[m  [32m                         Server.java:  369[m
                                   [37morg.eclipse.jetty.server.handler.HandlerWrapper.handle[m  [32m                 HandlerWrapper.java:  116[m
[37mring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle[m  [32m                                          [m
                                                      [33mring.adapter.jetty/proxy-handler/[1;33mfn[m  [32m                           jetty.clj:   20[m
                                                  [33mring.middleware.session/wrap-session/[1;33mfn[m  [32m                         session.clj:   98[m
                                                      [33mring.middleware.flash/wrap-flash/[1;33mfn[m  [32m                           flash.clj:   35[m
                                [33mring.middleware.multipart-params/wrap-multipart-params/[1;33mfn[m  [32m                multipart_params.clj:  118[m
                                                    [33mring.middleware.params/wrap-params/[1;33mfn[m  [32m                          params.clj:   64[m
                                      [33mring.middleware.nested-params/wrap-nested-params/[1;33mfn[m  [32m                   nested_params.clj:   84[m
                                    [33mring.middleware.keyword-params/wrap-keyword-params/[1;33mfn[m  [32m                  keyword_params.clj:   35[m
                                                          [33mhsbox.handler/wrap-exception/[1;33mfn[m  [32m                         handler.clj:  130[m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                            core.clj:  132[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  626[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                             [33mcompojure.core/if-context/[1;33mfn[m  [32m                            core.clj:  198[m
                                                                         [33mhsbox.handler/[1;33mfn[m  [32m                         handler.clj:  124[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                        [33mring.middleware.cors/wrap-cors/[1;33mfn[m  [32m                            cors.clj:  150[m
                                                   [33mring.middleware.json/wrap-json-body/[1;33mfn[m  [32m                            json.clj:   35[m
                                               [33mring.middleware.json/wrap-json-response/[1;33mfn[m  [32m                            json.clj:   65[m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                            core.clj:  132[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  626[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                              [33mcompojure.core/if-method/[1;33mfn[m  [32m                            core.clj:   27[m
                                                               [33mcompojure.core/if-route/[1;33mfn[m  [32m                            core.clj:   41[m
                                                  [33mcompojure.core/wrap-route-middleware/[1;33mfn[m  [32m                            core.clj:  103[m
                                                             [33mcompojure.core/make-route/[1;33mfn[m  [32m                            core.clj:  113[m
                                                                         [33mhsbox.handler/[1;33mfn[m  [32m                         handler.clj:   85[m
                                                         [33mhsbox.steamapi/[1;33mget-steamids-info[m  [32m                        steamapi.clj:   43[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  624[m
                                                                         [33mclojure.core/[1;33mseq[m  [32m                            core.clj:  133[m
                                                                                      [37m...[m  [32m                                          [m
                                                                      [33mclojure.core/map/[1;33mfn[m  [32m                            core.clj: 2559[m
                                                [33mhsbox.steamapi/[1;33mget-steamids-info-from-api[m  [32m                        steamapi.clj:   18[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  624[m
                                                                                      [37m...[m  [32m                                          [m
                                                                  [33mwatt.core/method->fn/[1;33mfn[m  [32m                            core.clj:   51[m
                                                     [33mclj-http.client/wrap-unknown-host/[1;33mfn[m  [32m                          client.clj:  726[m
                                                             [33mclj-http.links/wrap-links/[1;33mfn[m  [32m                           links.clj:   50[m
                                                         [33mclj-http.cookies/wrap-cookies/[1;33mfn[m  [32m                         cookies.clj:  122[m
                                                           [33mclj-http.client/wrap-method/[1;33mfn[m  [32m                          client.clj:  624[m
                                                    [33mclj-http.client/wrap-nested-params/[1;33mfn[m  [32m                          client.clj:  707[m
                                                      [33mclj-http.client/wrap-form-params/[1;33mfn[m  [32m                          client.clj:  683[m
                                                     [33mclj-http.client/wrap-content-type/[1;33mfn[m  [32m                          client.clj:  512[m
                                                  [33mclj-http.client/wrap-accept-encoding/[1;33mfn[m  [32m                          client.clj:  536[m
                                                           [33mclj-http.client/wrap-accept/[1;33mfn[m  [32m                          client.clj:  522[m
                                                       [33mclj-http.client/wrap-exceptions/[1;33mfn[m  [32m                          client.clj:  164[m
                                                  [33mclj-http.client/wrap-output-coercion/[1;33mfn[m  [32m                          client.clj:  398[m
                                        [33mclj-http.client/wrap-additional-header-parsing/[1;33mfn[m  [32m                          client.clj:  494[m
                                                   [33mclj-http.client/wrap-input-coercion/[1;33mfn[m  [32m                          client.clj:  445[m
                                                    [33mclj-http.client/wrap-decompression/[1;33mfn[m  [32m                          client.clj:  284[m
                                                        [33mclj-http.client/wrap-redirects/[1;33mfn[m  [32m                          client.clj:  212[m
                                                              [33mclj-http.client/wrap-url/[1;33mfn[m  [32m                          client.clj:  717[m
                                                        [33mclj-http.client/wrap-user-info/[1;33mfn[m  [32m                          client.clj:  617[m
                                                            [33mclj-http.client/wrap-oauth/[1;33mfn[m  [32m                          client.clj:  604[m
                                                       [33mclj-http.client/wrap-basic-auth/[1;33mfn[m  [32m                          client.clj:  594[m
                                                     [33mclj-http.client/wrap-query-params/[1;33mfn[m  [32m                          client.clj:  577[m
                                                      [33mclj-http.headers/wrap-header-map/[1;33mfn[m  [32m                         headers.clj:  138[m
                                                   [33mclj-http.client/wrap-request-timing/[1;33mfn[m  [32m                          client.clj:  751[m
                                                                                      [37m...[m  [32m                                          [m
                                                                    [33mclj-http.core/[1;33mrequest[m  [32m                            core.clj:  289[m
                                  [37morg.apache.http.impl.client.CloseableHttpClient.execute[m  [32m            CloseableHttpClient.java:  106[m
                                  [37morg.apache.http.impl.client.CloseableHttpClient.execute[m  [32m            CloseableHttpClient.java:   82[m
                                 [37morg.apache.http.impl.client.AbstractHttpClient.doExecute[m  [32m             AbstractHttpClient.java:  863[m
                               [37morg.apache.http.impl.client.DefaultRequestDirector.execute[m  [32m         DefaultRequestDirector.java:  446[m
                            [37morg.apache.http.impl.client.DefaultRequestDirector.tryConnect[m  [32m         DefaultRequestDirector.java:  611[m
                               [37morg.apache.http.impl.conn.ManagedClientConnectionImpl.open[m  [32m    ManagedClientConnectionImpl.java:  304[m
                 [37morg.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection[m  [32mDefaultClientConnectionOperator.java:  177[m
                             [37morg.apache.http.conn.scheme.PlainSocketFactory.connectSocket[m  [32m             PlainSocketFactory.java:  117[m
                                                                  [37mjava.net.Socket.connect[m  [32m                                          [m
                                                         [37mjava.net.SocksSocketImpl.connect[m  [32m                                          [m
                                                         [37mjava.net.PlainSocketImpl.connect[m  [32m                                          [m
                                                 [37mjava.net.AbstractPlainSocketImpl.connect[m  [32m                                          [m
                                        [37mjava.net.AbstractPlainSocketImpl.connectToAddress[m  [32m                                          [m
                                               [37mjava.net.AbstractPlainSocketImpl.doConnect[m  [32m                                          [m
                                          [37mjava.net.DualStackPlainSocketImpl.socketConnect[m  [32m                                          [m
                                               [37mjava.net.DualStackPlainSocketImpl.connect0[m  [32m                                          [m
[1;31mjava.net.ConnectException[m: [3mConnection timed out: connect[m

2015-Oct-31 01:51:08 +1000 Death ERROR [hsbox.handler] - 
                                                                     [37mjava.lang.Thread.run[m  [32m                                          [m
                                     [37morg.eclipse.jetty.util.thread.QueuedThreadPool$3.run[m  [32m               QueuedThreadPool.java:  543[m
                                    [37morg.eclipse.jetty.util.thread.QueuedThreadPool.runJob[m  [32m               QueuedThreadPool.java:  608[m
                                     [37morg.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run[m  [32m          SelectChannelEndPoint.java:   52[m
                                    [37morg.eclipse.jetty.io.nio.SelectChannelEndPoint.handle[m  [32m          SelectChannelEndPoint.java:  668[m
                                      [37morg.eclipse.jetty.server.AsyncHttpConnection.handle[m  [32m            AsyncHttpConnection.java:   82[m
                                         [37morg.eclipse.jetty.http.HttpParser.parseAvailable[m  [32m                     HttpParser.java:  235[m
                                              [37morg.eclipse.jetty.http.HttpParser.parseNext[m  [32m                     HttpParser.java:  644[m
            [37morg.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete[m  [32m         AbstractHttpConnection.java:  995[m
                           [37morg.eclipse.jetty.server.AbstractHttpConnection.headerComplete[m  [32m         AbstractHttpConnection.java:  933[m
                            [37morg.eclipse.jetty.server.AbstractHttpConnection.handleRequest[m  [32m         AbstractHttpConnection.java:  486[m
                                                   [37morg.eclipse.jetty.server.Server.handle[m  [32m                         Server.java:  369[m
                                   [37morg.eclipse.jetty.server.handler.HandlerWrapper.handle[m  [32m                 HandlerWrapper.java:  116[m
[37mring.adapter.jetty.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle[m  [32m                                          [m
                                                      [33mring.adapter.jetty/proxy-handler/[1;33mfn[m  [32m                           jetty.clj:   20[m
                                                  [33mring.middleware.session/wrap-session/[1;33mfn[m  [32m                         session.clj:   98[m
                                                      [33mring.middleware.flash/wrap-flash/[1;33mfn[m  [32m                           flash.clj:   35[m
                                [33mring.middleware.multipart-params/wrap-multipart-params/[1;33mfn[m  [32m                multipart_params.clj:  118[m
                                                    [33mring.middleware.params/wrap-params/[1;33mfn[m  [32m                          params.clj:   64[m
                                      [33mring.middleware.nested-params/wrap-nested-params/[1;33mfn[m  [32m                   nested_params.clj:   84[m
                                    [33mring.middleware.keyword-params/wrap-keyword-params/[1;33mfn[m  [32m                  keyword_params.clj:   35[m
                                                          [33mhsbox.handler/wrap-exception/[1;33mfn[m  [32m                         handler.clj:  130[m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                            core.clj:  132[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  626[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                             [33mcompojure.core/if-context/[1;33mfn[m  [32m                            core.clj:  198[m
                                                                         [33mhsbox.handler/[1;33mfn[m  [32m                         handler.clj:  124[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                        [33mring.middleware.cors/wrap-cors/[1;33mfn[m  [32m                            cors.clj:  150[m
                                                   [33mring.middleware.json/wrap-json-body/[1;33mfn[m  [32m                            json.clj:   35[m
                                               [33mring.middleware.json/wrap-json-response/[1;33mfn[m  [32m                            json.clj:   65[m
                                                                 [33mcompojure.core/routes/[1;33mfn[m  [32m                            core.clj:  132[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  626[m
                                                                                      [37m...[m  [32m                                          [m
                                                                   [33mcompojure.core/[1;33mrouting[m  [32m                            core.clj:  127[m
                                                                        [33mclojure.core/[1;33msome[m  [32m                            core.clj: 2515[m
                                                                [33mcompojure.core/routing/[1;33mfn[m  [32m                            core.clj:  127[m
                                                              [33mcompojure.core/if-method/[1;33mfn[m  [32m                            core.clj:   27[m
                                                               [33mcompojure.core/if-route/[1;33mfn[m  [32m                            core.clj:   41[m
                                                  [33mcompojure.core/wrap-route-middleware/[1;33mfn[m  [32m                            core.clj:  103[m
                                                             [33mcompojure.core/make-route/[1;33mfn[m  [32m                            core.clj:  113[m
                                                                         [33mhsbox.handler/[1;33mfn[m  [32m                         handler.clj:   85[m
                                                         [33mhsbox.steamapi/[1;33mget-steamids-info[m  [32m                        steamapi.clj:   43[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  624[m
                                                                         [33mclojure.core/[1;33mseq[m  [32m                            core.clj:  133[m
                                                                                      [37m...[m  [32m                                          [m
                                                                      [33mclojure.core/map/[1;33mfn[m  [32m                            core.clj: 2559[m
                                                [33mhsbox.steamapi/[1;33mget-steamids-info-from-api[m  [32m                        steamapi.clj:   18[m
                                                                       [33mclojure.core/[1;33mapply[m  [32m                            core.clj:  624[m
                                                                                      [37m...[m  [32m                                          [m
                                                                  [33mwatt.core/method->fn/[1;33mfn[m  [32m                            core.clj:   51[m
                                                     [33mclj-http.client/wrap-unknown-host/[1;33mfn[m  [32m                          client.clj:  726[m
                                                             [33mclj-http.links/wrap-links/[1;33mfn[m  [32m                           links.clj:   50[m
                                                         [33mclj-http.cookies/wrap-cookies/[1;33mfn[m  [32m                         cookies.clj:  122[m
                                                           [33mclj-http.client/wrap-method/[1;33mfn[m  [32m                          client.clj:  624[m
                                                    [33mclj-http.client/wrap-nested-params/[1;33mfn[m  [32m                          client.clj:  707[m
                                                      [33mclj-http.client/wrap-form-params/[1;33mfn[m  [32m                          client.clj:  683[m
                                                     [33mclj-http.client/wrap-content-type/[1;33mfn[m  [32m                          client.clj:  512[m
                                                  [33mclj-http.client/wrap-accept-encoding/[1;33mfn[m  [32m                          client.clj:  536[m
                                                           [33mclj-http.client/wrap-accept/[1;33mfn[m  [32m                          client.clj:  522[m
                                                       [33mclj-http.client/wrap-exceptions/[1;33mfn[m  [32m                          client.clj:  164[m
                                                  [33mclj-http.client/wrap-output-coercion/[1;33mfn[m  [32m                          client.clj:  398[m
                                        [33mclj-http.client/wrap-additional-header-parsing/[1;33mfn[m  [32m                          client.clj:  494[m
                                                   [33mclj-http.client/wrap-input-coercion/[1;33mfn[m  [32m                          client.clj:  445[m
                                                    [33mclj-http.client/wrap-decompression/[1;33mfn[m  [32m                          client.clj:  284[m
                                                        [33mclj-http.client/wrap-redirects/[1;33mfn[m  [32m                          client.clj:  212[m
                                                              [33mclj-http.client/wrap-url/[1;33mfn[m  [32m                          client.clj:  717[m
                                                        [33mclj-http.client/wrap-user-info/[1;33mfn[m  [32m                          client.clj:  617[m
                                                            [33mclj-http.client/wrap-oauth/[1;33mfn[m  [32m                          client.clj:  604[m
                                                       [33mclj-http.client/wrap-basic-auth/[1;33mfn[m  [32m                          client.clj:  594[m
                                                     [33mclj-http.client/wrap-query-params/[1;33mfn[m  [32m                          client.clj:  577[m
                                                      [33mclj-http.headers/wrap-header-map/[1;33mfn[m  [32m                         headers.clj:  138[m
                                                   [33mclj-http.client/wrap-request-timing/[1;33mfn[m  [32m                          client.clj:  751[m
                                                                                      [37m...[m  [32m                                          [m
                                                                    [33mclj-http.core/[1;33mrequest[m  [32m                            core.clj:  289[m
                                  [37morg.apache.http.impl.client.CloseableHttpClient.execute[m  [32m            CloseableHttpClient.java:  106[m
                                  [37morg.apache.http.impl.client.CloseableHttpClient.execute[m  [32m            CloseableHttpClient.java:   82[m
                                 [37morg.apache.http.impl.client.AbstractHttpClient.doExecute[m  [32m             AbstractHttpClient.java:  863[m
                               [37morg.apache.http.impl.client.DefaultRequestDirector.execute[m  [32m         DefaultRequestDirector.java:  446[m
                            [37morg.apache.http.impl.client.DefaultRequestDirector.tryConnect[m  [32m         DefaultRequestDirector.java:  611[m
                               [37morg.apache.http.impl.conn.ManagedClientConnectionImpl.open[m  [32m    ManagedClientConnectionImpl.java:  304[m
                 [37morg.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection[m  [32mDefaultClientConnectionOperator.java:  177[m
                             [37morg.apache.http.conn.scheme.PlainSocketFactory.connectSocket[m  [32m             PlainSocketFactory.java:  117[m
                                                                  [37mjava.net.Socket.connect[m  [32m                                          [m
                                                         [37mjava.net.SocksSocketImpl.connect[m  [32m                                          [m
                                                         [37mjava.net.PlainSocketImpl.connect[m  [32m                                          [m
                                                 [37mjava.net.AbstractPlainSocketImpl.connect[m  [32m                                          [m
                                        [37mjava.net.AbstractPlainSocketImpl.connectToAddress[m  [32m                                          [m
                                               [37mjava.net.AbstractPlainSocketImpl.doConnect[m  [32m                                          [m
                                          [37mjava.net.DualStackPlainSocketImpl.socketConnect[m  [32m                                          [m
                                               [37mjava.net.DualStackPlainSocketImpl.connect0[m  [32m                                          [m
[1;31mjava.net.ConnectException[m: [3mConnection timed out: connect[m

**Comment by bugdone** [comment]
It looks like it cannot connect to the steam api. Seems to be a connectivity issue.

**Comment by Mo0shi** [comment]
Anything I can do?
I've reset my API key, reset my router, reset my computer.
Still happening.

**Comment by bugdone** [comment]
I don't think this has to do anything with the API key.
What does `telnet api.steampowered.com 80` say?

**Comment by Mo0shi** [comment]
>telnet api.steampowered.com 80
Connecting To api.steampowered.com...Could not open connection to the host, on port 80: Connect failed

so no luck there. :\

**Comment by Mo0shi** [comment]
Used a VPN server in the states, and it managed to retrieve fresh data from the steam api.
Something is preventing my connection from reaching the steam api somewhere down the line, so definitely not an issue with hsb.

Love the work you do, and live hsb!
