### ISSUE TITLE
Watch Demo Button

### ISSUE THREAD

**Issue by Kruemmelmonster** [bugdone/headshotbox#95]
is there a way to implement downloading the demo and starting that instead of trying to find the demo in the path as it is on the server?

because on my vps the demos are in ~/demos and on my windows machine when i click on watch it tries to find the demo in ~/demos (wich doesnt exist)

thanks in advance
~kru

**Comment by bugdone** [comment]
Partially covered by web mode in 0.12.
I don't think it's possible to download files automatically. It would be very scary if a browser would to do that.
