### ISSUE TITLE
Cannot Open Server Demos

### ISSUE THREAD

**Issue by Twistedwheelbarrow** [bugdone/headshotbox#96]
I don't know if this is even supported, as it does not make it fully clear. We host a server with the GOTV enabled so that demos are automatically recorded to the server. I have downloaded it and placed it within the scanned folder, but it says "Unknown Demo Type" at the bottom of the batch file.

Is there a fix for this, or does it just not work? Thanks.

**Comment by bugdone** [comment]
It doesn't work by design. See https://github.com/bugdone/headshotbox/issues/65#issuecomment-121368971
