### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by kymatica** [bugdone/headshotbox#98]
Firstly -- Awesome looking project!

Just trying to get this to run on my Raspberry Pi, mainly so I don't have to install Java on my Windows PC.
Headshotbox doesn't seem to save any of my settings.
The 'Demo directory' will be /mnt/CSGO (Mounted NFS share from 192.168.x.y/csgo)

Looking at the logs it's throwing up the following error whenever it launches or if I hit 'submit' in settings:

java.lang.Exception: Error loading native library: /org/sqlite/native/Linux/arm/libsqlitejdbc.so
java.sql.SQLException: Error opening connection

Anything you could help me with? 

Thank you!

**Comment by yoyosan** [comment]
Hey @kymatica 

Check the section regarding SQLite JDBC in this [article](http://pidome.org/info/blog-news/2013/10/1/java-goes-hard-on-the-raspberry-pi-so-does-pidome.html).

**Comment by kymatica** [comment]
Thanks for that! I hadn't come across that article in my searches.
Looking into it now!

**Comment by bugdone** [comment]
Maybe [this](https://bitbucket.org/xerial/sqlite-jdbc/issues/79/compile-for-arm) would help (you can also check the github issues of the project for more arm stuff).

After you manage to get an arm sqlite jdbc, you still have to:
* figure out how to build headshotbox with your jdbc jar
* compile demoinfogo for arm

**Comment by kymatica** [comment]
Thanks for getting back to me!

Too ambitious of an idea to use my Pi instead of my PC?
I'll have a quick look, but if it's as you say it is.. i'll probably end up using my Windows PC.

**Comment by bugdone** [comment]
Well, nothing is impossible :)

There are two binaries in headshotbox:
* [demoinfogo](https://github.com/bugdone/demoinfogo-linux)
* sqlite jdbc (java project but uses a binary)

If you don't use one of the builds I provide (linux x86 or win x86), you have to compile them for your platform.

**Comment by kymatica** [comment]
Thanks for the info, and again, nice work on the project!
Appreciate you helping me out!
